import { type TimeSlot, type DaySchedule } from "./tv-channels";

// Animax Asia weekly schedule (IST times, converted from HKT)
// Source: Now TV / Animax Asia official schedule
// Schedule is a fixed weekly rotation that updates when anime seasons change
// Last updated: July 2026

const ANIMAX_WEEKLY: Record<string, TimeSlot[]> = {
  Monday: [
    { show: "Ragna Crimson S1E6 -Reunion", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "Ragna Crimson S1E7 -Pretence And Accusation", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "Ragna Crimson S1E8 -Hard Blow", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "Ragna Crimson S1E9 -Negotiation And True Nature", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "20:30", end: "21:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "21:00", end: "21:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "21:30", end: "22:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "22:00", end: "22:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "22:30", end: "23:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "23:00", end: "23:30", duration: 30, description: "Animax Asia" },
  ],
  Tuesday: [
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E40 -Rose Of Restless Souls", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E40 -Rose Of Restless Souls", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E3", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "20:30", end: "21:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "21:00", end: "21:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "21:30", end: "22:00", duration: 30, description: "Animax Asia" },
  ],
  Wednesday: [
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E40 -Rose Of Restless Souls", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E3", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E36 -Chapter Of Darkness", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E37 -The Neighborhood Boy", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E38 -Froi Tiedoll", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E40 -Rose Of Restless Souls", start: "20:30", end: "21:00", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E6 -We'll Figure It Out", start: "21:00", end: "21:30", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E7 -Tackling Awkward Situations", start: "21:30", end: "22:00", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E8 -Produce Results", start: "22:00", end: "22:30", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E9 -Showing Off", start: "22:30", end: "23:00", duration: 30, description: "Animax Asia" },
  ],
  Thursday: [
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E1", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E3", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "20:30", end: "21:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "21:00", end: "21:30", duration: 30, description: "Animax Asia" },
  ],
  Friday: [
    { show: "Oshi No Ko S1E4 -Actors", start: "06:30", end: "07:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "07:00", end: "07:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "07:30", end: "08:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "08:00", end: "08:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "08:30", end: "09:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "09:00", end: "09:30", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E6 -We'll Figure It Out", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E7 -Tackling Awkward Situations", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E8 -Produce Results", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E9 -Showing Off", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E4 -Actors", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E38 -Froi Tiedoll", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E1", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E4 -Actors", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E38 -Froi Tiedoll", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E1", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E40 -Rose Of Restless Souls", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "20:30", end: "21:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "21:00", end: "21:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "21:30", end: "22:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E3", start: "22:00", end: "22:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "22:30", end: "23:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "23:00", end: "23:30", duration: 30, description: "Animax Asia" },
  ],
  Saturday: [
    { show: "D.Gray-Man S1E36 -Chapter Of Darkness", start: "01:00", end: "01:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E37 -The Neighborhood Boy", start: "01:30", end: "02:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E38 -Froi Tiedoll", start: "02:00", end: "02:30", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E39 -Coffin Of Silence", start: "02:30", end: "03:00", duration: 30, description: "Animax Asia" },
    { show: "D.Gray-Man S1E40 -Rose Of Restless Souls", start: "03:00", end: "03:30", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E6 -We'll Figure It Out", start: "03:30", end: "04:00", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E7 -Tackling Awkward Situations", start: "04:00", end: "04:30", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E8 -Produce Results", start: "04:30", end: "05:00", duration: 30, description: "Animax Asia" },
    { show: "Remake Our Life! S1E9 -Showing Off", start: "05:00", end: "05:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "05:30", end: "06:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "06:00", end: "06:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "06:30", end: "07:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "07:00", end: "07:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "07:30", end: "08:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "08:00", end: "08:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "08:30", end: "09:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "09:00", end: "09:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "20:30", end: "21:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "21:00", end: "21:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "21:30", end: "22:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "22:00", end: "22:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "22:30", end: "23:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "23:00", end: "23:30", duration: 30, description: "Animax Asia" },
  ],
  Sunday: [
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E1", start: "01:30", end: "02:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "02:00", end: "02:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E3", start: "02:30", end: "03:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "03:00", end: "03:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "03:30", end: "04:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "04:00", end: "04:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "04:30", end: "05:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "05:00", end: "05:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "05:30", end: "06:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "06:00", end: "06:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "06:30", end: "07:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E1", start: "07:00", end: "07:30", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E2", start: "07:30", end: "08:00", duration: 30, description: "Animax Asia" },
    { show: "Why Raeliana Ended Up At The Duke's Mansion S1E3", start: "08:00", end: "08:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "08:30", end: "09:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "09:00", end: "09:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "09:30", end: "10:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "10:00", end: "10:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "10:30", end: "11:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "11:00", end: "11:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "11:30", end: "12:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "12:00", end: "12:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "12:30", end: "13:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "13:00", end: "13:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "13:30", end: "14:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "14:00", end: "14:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E7 -Justice For The Winners!", start: "14:30", end: "15:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E8 -Straw Hat Team Arrives!", start: "15:00", end: "15:30", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E9 -Luffy Vs. The Navy", start: "15:30", end: "16:00", duration: 30, description: "Animax Asia" },
    { show: "One Piece: Marineford Arc S1E10 -Devil Fruit Eaters Vs. Devil Fruit Eaters!", start: "16:00", end: "16:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E13 -The Wizard King Saw, Continued", start: "16:30", end: "17:00", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E14 -Dungeon", start: "17:00", end: "17:30", duration: 30, description: "Animax Asia" },
    { show: "Black Clover S1E15 -The Diamond Mage", start: "17:30", end: "18:00", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E5 -Reality Dating Show", start: "18:00", end: "18:30", duration: 30, description: "Animax Asia" },
    { show: "Oshi No Ko S1E6 -Egosurfing", start: "18:30", end: "19:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E16 -Unseen Visage", start: "19:00", end: "19:30", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E17 -Returning The Promise", start: "19:30", end: "20:00", duration: 30, description: "Animax Asia" },
    { show: "Unnamed Memory S2E18 -Bloodless Scars", start: "20:00", end: "20:30", duration: 30, description: "Animax Asia" },
  ],
};

const ALL_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export function getAnimaxSchedule(): { channelId: string; schedules: DaySchedule[] } {
  return {
    channelId: "animax",
    schedules: ALL_DAYS.map((d) => ({ day: d, slots: ANIMAX_WEEKLY[d] || [] })),
  };
}
