import type { ScrapedAward } from "./awards-scraper";

// Curated, verified winners of the Crunchyroll Anime Awards (2022–2025).
// Used as a reliable fallback so the admin panel always has real data,
// even when live scraping fails.
export const CURATED_AWARDS: ScrapedAward[] = [
  // ── Crunchyroll Anime Awards 2025 (for 2024 anime) ──
  { year: 2025, category: "Anime of the Year", winner: "Solo Leveling", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best New Anime Series", winner: "Solo Leveling", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Action", winner: "Solo Leveling", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Animation", winner: "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Character Design", winner: "DAN DA DAN", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Director", winner: "Keiichirō Saitō — Frieren: Beyond Journey's End", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Background Art", winner: "Frieren: Beyond Journey's End", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Drama", winner: "Frieren: Beyond Journey's End", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Fantasy", winner: "Frieren: Beyond Journey's End", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Comedy", winner: "MASHLE: MAGIC AND MUSCLES The Divine Visionary Candidate Exam Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Romance", winner: "Blue Box", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Isekai", winner: "Re:ZERO -Starting Life in Another World- Season 3", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Slice of Life", winner: "MAKEINE: Too Many Losing Heroines!", platform: "Crunchyroll", type: "anime" },
  { year: 2025, category: "Best Main Character", winner: "Sung Jinwoo — Solo Leveling", platform: "Crunchyroll", type: "character" },
  { year: 2025, category: "Best Supporting Character", winner: "Fern — Frieren: Beyond Journey's End", platform: "Crunchyroll", type: "character" },
  { year: 2025, category: "Best Anime Song", winner: "\"Otonoke\" by Creepy Nuts — DAN DA DAN", platform: "Crunchyroll", type: "music" },
  { year: 2025, category: "Best Score", winner: "Hiroyuki Sawano — Solo Leveling", platform: "Crunchyroll", type: "music" },
  { year: 2025, category: "Best Voice Artist (Japanese)", winner: "Aoi Yūki (Maomao) — The Apothecary Diaries", platform: "Crunchyroll", type: "character" },
  { year: 2025, category: "Best Voice Artist (English)", winner: "Aleks Le (Sung Jinwoo) — Solo Leveling", platform: "Crunchyroll", type: "character" },

  // ── Crunchyroll Anime Awards 2024 (for 2023 anime) ──
  { year: 2024, category: "Anime of the Year", winner: "Jujutsu Kaisen: Hidden Inventory/Premature Death", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Action", winner: "Jujutsu Kaisen: Hidden Inventory/Premature Death", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Animation", winner: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Anime Song", winner: "\"Idol\" by YOASOBI — Oshi no Ko", platform: "Crunchyroll", type: "music" },
  { year: 2024, category: "Best Art Direction", winner: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Character Design", winner: "Sayaka Koiso, Tadashi Hiramatsu — Jujutsu Kaisen Season 2", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Cinematography", winner: "Jujutsu Kaisen: Hidden Inventory/Premature Death", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Comedy", winner: "Spy x Family Season 1 Cour 2", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Continuing Series", winner: "One Piece", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Director", winner: "Shota Goshozono — Jujutsu Kaisen Season 2", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Drama", winner: "Attack on Titan: The Final Chapters Special 1", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Ending Sequence", winner: "\"Akari\" by Soshi Sakiyama — Jujutsu Kaisen Season 2", platform: "Crunchyroll", type: "music" },
  { year: 2024, category: "Best Fantasy", winner: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Film", winner: "Suzume", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Main Character", winner: "Monkey D. Luffy — One Piece", platform: "Crunchyroll", type: "character" },
  { year: 2024, category: "Best New Series", winner: "Chainsaw Man", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Opening Sequence", winner: "\"Where Our Blue Is\" by Tatsuya Kitani — Jujutsu Kaisen Season 2", platform: "Crunchyroll", type: "music" },
  { year: 2024, category: "Best Original Anime", winner: "Buddy Daddies", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Romance", winner: "Horimiya: The Missing Pieces", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Score", winner: "Attack on Titan: The Final Chapters Special 1", platform: "Crunchyroll", type: "music" },
  { year: 2024, category: "Best Slice of Life", winner: "Bocchi the Rock!", platform: "Crunchyroll", type: "anime" },
  { year: 2024, category: "Best Supporting Character", winner: "Satoru Gojo — Jujutsu Kaisen Season 2", platform: "Crunchyroll", type: "character" },
  { year: 2024, category: "Best Voice Artist (Japanese)", winner: "Yuichi Nakamura (Satoru Gojo) — Jujutsu Kaisen Season 2", platform: "Crunchyroll", type: "character" },
  { year: 2024, category: "Best Voice Artist (English)", winner: "Ryan Colt Levy (Denji) — Chainsaw Man", platform: "Crunchyroll", type: "character" },

  // ── Crunchyroll Anime Awards 2023 (for 2022 anime) ──
  { year: 2023, category: "Anime of the Year", winner: "Cyberpunk: Edgerunners", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Action", winner: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Animation", winner: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Anime Song", winner: "\"The Rumbling\" by SiM — Attack on Titan Final Season Part 2", platform: "Crunchyroll", type: "music" },
  { year: 2023, category: "Best Character Design", winner: "Akira Matsushima — Demon Slayer: Entertainment District Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Comedy", winner: "Spy x Family", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Continuing Series", winner: "One Piece", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Director", winner: "Haruo Sotozaki — Demon Slayer: Entertainment District Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Drama", winner: "Attack on Titan Final Season Part 2", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Ending Sequence", winner: "\"Comedy\" by Gen Hoshino — Spy x Family", platform: "Crunchyroll", type: "music" },
  { year: 2023, category: "Best Fantasy", winner: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Film", winner: "Jujutsu Kaisen 0", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Main Character", winner: "Eren Jaeger — Attack on Titan Final Season Part 2", platform: "Crunchyroll", type: "character" },
  { year: 2023, category: "Best New Series", winner: "Spy x Family", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Opening Sequence", winner: "\"The Rumbling\" by SiM — Attack on Titan Final Season Part 2", platform: "Crunchyroll", type: "music" },
  { year: 2023, category: "Best Original Anime", winner: "Lycoris Recoil", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Romance", winner: "Kaguya-sama: Love is War Ultra Romantic", platform: "Crunchyroll", type: "anime" },
  { year: 2023, category: "Best Score", winner: "KOHTA YAMAMOTO & Hiroyuki Sawano — Attack on Titan Final Season Part 2", platform: "Crunchyroll", type: "music" },
  { year: 2023, category: "Best Supporting Character", winner: "Anya Forger — Spy x Family", platform: "Crunchyroll", type: "character" },
  { year: 2023, category: "Best Voice Artist (English)", winner: "Zach Aguilar (David Martinez) — Cyberpunk: Edgerunners", platform: "Crunchyroll", type: "character" },
  { year: 2023, category: "Best Voice Artist (Japanese)", winner: "Yūki Kaji (Eren Jaeger) — Attack on Titan Final Season Part 2", platform: "Crunchyroll", type: "character" },

  // ── Crunchyroll Anime Awards 2022 (for 2021 anime) ──
  { year: 2022, category: "Anime of the Year", winner: "Attack on Titan Final Season Part 1", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Action", winner: "Jujutsu Kaisen (Cour 2)", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Animation", winner: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Boy", winner: "Bojji — Ranking of Kings", platform: "Crunchyroll", type: "character" },
  { year: 2022, category: "Best Girl", winner: "Nobara Kugisaki — Jujutsu Kaisen (Cour 2)", platform: "Crunchyroll", type: "character" },
  { year: 2022, category: "Best Protagonist", winner: "Odokawa — Odd Taxi", platform: "Crunchyroll", type: "character" },
  { year: 2022, category: "Best Antagonist", winner: "Eren Jaeger — Attack on Titan Final Season Part 1", platform: "Crunchyroll", type: "character" },
  { year: 2022, category: "Best Fight Scene", winner: "Yuji Itadori & Aoi Todo vs Hanami — Jujutsu Kaisen (Cour 2)", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Director", winner: "Baku Kinoshita — Odd Taxi", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Character Design", winner: "Tadashi Hiramatsu — Jujutsu Kaisen (Cour 2)", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Score", winner: "Yuki Kajiura & Go Shiina — Demon Slayer: Mugen Train Arc", platform: "Crunchyroll", type: "music" },
  { year: 2022, category: "Best Opening Sequence", winner: "\"Boku no Sensou\" by Shinsei Kamattechan — Attack on Titan Final Season Part 1", platform: "Crunchyroll", type: "music" },
  { year: 2022, category: "Best Ending Sequence", winner: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", platform: "Crunchyroll", type: "music" },
  { year: 2022, category: "Best Comedy", winner: "Komi Can't Communicate", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Drama", winner: "To Your Eternity", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Fantasy", winner: "That Time I Got Reincarnated as a Slime Season 2", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Romance", winner: "Horimiya", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Film", winner: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", platform: "Crunchyroll", type: "anime" },
  { year: 2022, category: "Best Voice Artist (Japanese)", winner: "Yuki Kaji (Eren Jaeger) — Attack on Titan Final Season Part 1", platform: "Crunchyroll", type: "character" },
  { year: 2022, category: "Best Voice Artist (English)", winner: "David Wald (ADAM) — SK8 the Infinity", platform: "Crunchyroll", type: "character" },
];
