export interface PodcastEpisode {
  id: string;
  title: string;
  description: string;
  duration: string;
  publishDate: string;
  youtubeId: string;
  channel: string;
  channelUrl: string;
  tags: string[];
  language: "en" | "hi" | "both";
}

export const PODCAST_EPISODES: PodcastEpisode[] = [
  {
    id: "tt-317",
    title: "Anime That Defined a Generation",
    description: "The boys discuss which anime truly defined a generation and shaped the fandom we know today. From Naruto to One Piece, which series left the biggest impact on anime culture worldwide?",
    duration: "01:54:30",
    publishDate: "2026-07-17",
    youtubeId: "HspcPE_snRo",
    channel: "Trash Taste",
    channelUrl: "https://www.youtube.com/@TrashTaste",
    tags: ["Trash Taste", "Discussion", "Culture"],
    language: "en",
  },
  {
    id: "tt-314",
    title: "Gamers Are Eating Good in 2026",
    description: "The crew talks about the incredible lineup of anime-inspired games releasing in 2026, plus their personal gaming experiences and the state of gaming culture.",
    duration: "01:52:00",
    publishDate: "2026-06-26",
    youtubeId: "ZkBTTlH7bBU",
    channel: "Trash Taste",
    channelUrl: "https://www.youtube.com/@TrashTaste",
    tags: ["Trash Taste", "Gaming", "2026"],
    language: "en",
  },
  {
    id: "tt-309",
    title: "Collecting Doesn't Feel the Same Anymore",
    description: "From manga collections to vintage anime merch, the boys explore why collecting anime memorabilia has changed and whether the joy of collecting is still the same.",
    duration: "01:57:24",
    publishDate: "2026-05-22",
    youtubeId: "s5kOzMdG-mc",
    channel: "Trash Taste",
    channelUrl: "https://www.youtube.com/@TrashTaste",
    tags: ["Trash Taste", "Collecting", "Manga"],
    language: "en",
  },
  {
    id: "otn-104",
    title: "2026 Summer Anime GO!",
    description: "The Otaku Network breaks down all the must-watch anime of Summer 2026. From returning favorites to exciting new series, find out what's worth your time this season.",
    duration: "01:30:00",
    publishDate: "2026-07-10",
    youtubeId: "RBpJ58s5pjI",
    channel: "The Otaku Network",
    channelUrl: "https://www.youtube.com/@TheOtakuNetwork",
    tags: ["Seasonal", "Summer 2026", "First Impressions"],
    language: "en",
  },
  {
    id: "nlc-summer",
    title: "Summer 2026 Anime First Impressions",
    description: "No Level Cap Podcast covers Mushoku Tensei, Black Torch, Ghost in the Shell and more. Detailed first impressions and rankings for the Summer 2026 anime season.",
    duration: "01:15:00",
    publishDate: "2026-07-20",
    youtubeId: "CnI9-IrcTyo",
    channel: "No Level Cap",
    channelUrl: "https://www.youtube.com/@NoLevelCapPodcast",
    tags: ["Seasonal", "Summer 2026", "Review"],
    language: "en",
  },
  {
    id: "al-37",
    title: "Unveiling Japan's Challenges: An Indian's Guide",
    description: "An Indian cosplayer Nikkxie shares her experiences living in Japan — cultural shocks, language barriers, racism, cost of living, and why you shouldn't move to Japan just for anime.",
    duration: "01:21:30",
    publishDate: "2024-01-07",
    youtubeId: "Rvem7Gyv5sM",
    channel: "The Ani-Lyst Podcast",
    channelUrl: "https://www.youtube.com/@theanilystpodcast",
    tags: ["Ani-Lyst", "Japan", "Cosplay", "Lifestyle"],
    language: "en",
  },
  {
    id: "al-pokemon",
    title: "Pokemon India Collab & Anime Community",
    description: "The Ani-Lyst Podcast discusses Pokemon India collaborations, the growing Indian anime community, and what it takes to build an anime podcast from scratch in India.",
    duration: "01:10:00",
    publishDate: "2024-06-15",
    youtubeId: "qBB595CpqNE",
    channel: "The Ani-Lyst Podcast",
    channelUrl: "https://www.youtube.com/@theanilystpodcast",
    tags: ["Ani-Lyst", "Pokemon", "India", "Community"],
    language: "en",
  },
  {
    id: "cws-97",
    title: "Crunchyroll Anime Awards 2026 Discussion",
    description: "Chai with Senpai breaks down Crunchyroll Anime Awards 2026 nominations. City the Animation, Grand Blue snub, Solo Leveling debate, and hot takes with BeyondTheAryanVerse.",
    duration: "03:02:36",
    publishDate: "2026-05-23",
    youtubeId: "DxTRbld07wg",
    channel: "Chai with Senpai",
    channelUrl: "https://www.youtube.com/@ChaiwithSenpai",
    tags: ["Chai with Senpai", "Crunchyroll", "Awards 2026"],
    language: "hi",
  },
  {
    id: "mm-24hr",
    title: "The Struggles of 24-Hour Challenge Videos",
    description: "Sonal Kaushal (voice of Doraemon) talks about the hilarious struggles of doing 24-hour challenge videos with her daughter. Behind the scenes of Indian YouTube life.",
    duration: "00:56:00",
    publishDate: "2026-02-20",
    youtubeId: "fcJvoKCsHbA",
    channel: "The MotorMouth Show",
    channelUrl: "https://www.youtube.com/@Motormouth",
    tags: ["MotorMouth", "Doraemon", "YouTube", "Challenge"],
    language: "hi",
  },
  {
    id: "mm-mimicry",
    title: "When Actors Hear Their Own Mimicry",
    description: "Sonal Kaushal brings on Kettan Singh and they react to mimicry of Javed Akhtar and Farhan Akhtar. Hilarious voice acting moments from The MotorMouth Show.",
    duration: "00:01:14",
    publishDate: "2026-03-12",
    youtubeId: "F_7rUQBnu8Q",
    channel: "The MotorMouth Show",
    channelUrl: "https://www.youtube.com/@Motormouth",
    tags: ["MotorMouth", "Mimicry", "Voice Acting", "Funny"],
    language: "hi",
  },
  {
    id: "mm-class",
    title: "Class no Daikirai Voices Live!",
    description: "Manikant Sarbhoy joins The MotorMouth Show for a live voice acting session, performing scenes from Class no Daikirai anime in Hindi. Voice acting masterclass.",
    duration: "00:05:00",
    publishDate: "2026-01-20",
    youtubeId: "FY_zU2xNuqU",
    channel: "The MotorMouth Show",
    channelUrl: "https://www.youtube.com/@Motormouth",
    tags: ["MotorMouth", "Anime", "Hindi Dub", "Voice Acting"],
    language: "hi",
  },
  {
    id: "to-spring",
    title: "Spring 2026 Anime Preview — Witch Hat, Kill Blue & More",
    description: "The crew previews 9 brand new anime from Spring 2026 including Witch Hat Atelier, Kill Blue, Snowball Earth, and more. Which ones deserve your time?",
    duration: "01:55:37",
    publishDate: "2026-04-29",
    youtubeId: "XUwIfU59gNA",
    channel: "Taco Otaku",
    channelUrl: "https://www.youtube.com/@TacoOtakuBites",
    tags: ["Seasonal", "Spring 2026", "Preview"],
    language: "en",
  },
  {
    id: "to-summer46",
    title: "Summer Anime 2024 Review — Oshi no Ko, Elusive Samurai",
    description: "Taco Otaku breaks down Summer 2024 anime including Oshi no Ko Season 2, Pseudo Harem, and The Elusive Samurai. Full spoiler discussions and rankings.",
    duration: "02:36:00",
    publishDate: "2024-10-16",
    youtubeId: "E4PBzrNfZB8",
    channel: "Taco Otaku",
    channelUrl: "https://www.youtube.com/@TacoOtakuBites",
    tags: ["Taco Otaku", "Oshi no Ko", "Review", "Summer 2024"],
    language: "en",
  },
  {
    id: "am-summer",
    title: "Summer 2026 Anime Lineup is INSANE!",
    description: "Bleach TYBW Final Part, Mushoku Tensei S3, Tanya the Evil S2, Ghost in the Shell, and more. Complete Hindi breakdown of the biggest anime season of 2026.",
    duration: "00:04:55",
    publishDate: "2026-06-02",
    youtubeId: "am-summer-2026",
    channel: "Anime Manch",
    channelUrl: "https://www.youtube.com/@animemanch",
    tags: ["Anime Manch", "Summer 2026", "Lineup", "Hindi"],
    language: "hi",
  },
  {
    id: "am-updates",
    title: "Hindi Dubbed Anime Updates — Angel Next Door S2, Snowball Earth",
    description: "Latest Hindi dubbed anime episode releases: Angel Next Door S2 Ep 6, Snowball Earth Ep 6, Slime S4 updates and more from Anime Manch.",
    duration: "00:03:17",
    publishDate: "2026-05-30",
    youtubeId: "sYvkwiGieMY",
    channel: "Anime Manch",
    channelUrl: "https://www.youtube.com/@animemanch",
    tags: ["Anime Manch", "Hindi Dub", "Updates", "Weekly"],
    language: "hi",
  },
  {
    id: "am-hindi-may",
    title: "100+ New Hindi Dub Animes Released This May 2026",
    description: "Complete list of all Hindi dubbed anime released in May 2026 across MS India, Crunchyroll, AniTimes, JioHotstar, MX Player, Netflix and more.",
    duration: "00:08:00",
    publishDate: "2026-06-05",
    youtubeId: "rT5DBjRvPJ0",
    channel: "Anime Manch",
    channelUrl: "https://www.youtube.com/@animemanch",
    tags: ["Anime Manch", "Hindi Dub", "List", "May 2026"],
    language: "hi",
  },
  {
    id: "am-naruto-movie",
    title: "Hindi Dubbed Anime Update — Naruto Movie, Skeleton Knight & More",
    description: "Latest Hindi dubbed anime updates including Naruto movie, Skeleton Knight, Daemons of the Shadow Realm and more new releases.",
    duration: "00:05:00",
    publishDate: "2026-06-14",
    youtubeId: "YUdEet24eO8",
    channel: "Anime Manch",
    channelUrl: "https://www.youtube.com/@animemanch",
    tags: ["Anime Manch", "Naruto", "Hindi Dub", "Update"],
    language: "hi",
  },
  {
    id: "ae-supermarket",
    title: "Smoking Behind the Supermarket Ep 1 Explained in Hindi",
    description: "Animerehan breaks down Episode 1 of Smoking Behind the Supermarket With You in Hindi. A unique romance anime explained for Indian audiences.",
    duration: "00:15:00",
    publishDate: "2026-06-25",
    youtubeId: "38CGjU9B_Ck",
    channel: "Animerehan",
    channelUrl: "https://www.youtube.com/@Animerehan",
    tags: ["Animerehan", "Hindi", "Explanation", "Romance"],
    language: "hi",
  },
  {
    id: "av-real-life",
    title: "Which Anime Character Would You Bring Into Real Life?",
    description: "Animation Vibes asks anime fans and creators which anime character they'd bring to real life. Luffy, All Might, Eren, Thorfinn — the answers are wild!",
    duration: "00:01:19",
    publishDate: "2025-09-16",
    youtubeId: "PBSgmsD1O_8",
    channel: "Animation Vibes",
    channelUrl: "https://www.youtube.com/@AnimationVibes",
    tags: ["Animation Vibes", "Hindi", "Discussion", "Anime"],
    language: "hi",
  },
  {
    id: "tmms-shikamaru",
    title: "Live Dubbing Shikamaru & Gaara — ft. Manikant Sarbhoy",
    description: "Manikant Sarbhoy performs live dubbing of Shikamaru and Gaara scenes from Naruto in Hindi. An incredible voice acting showcase on The MotorMouth Show.",
    duration: "00:05:00",
    publishDate: "2026-02-15",
    youtubeId: "vAzcs3hii2s",
    channel: "The MotorMouth Show",
    channelUrl: "https://www.youtube.com/@Motormouth",
    tags: ["MotorMouth", "Naruto", "Hindi Dub", "Voice Acting", "Live Dubbing"],
    language: "hi",
  },
  {
    id: "fh-bluelock",
    title: "Blue Lock Voice Actors Interview — Bachira & Zantetsu",
    description: "FusionHaa Podcast interviews Matthew Elkins (Bachira) and Drew Breedlove (Zantetsu) from the Blue Lock English dub at Ba-con. How they got started, the anime phenomenon, and more.",
    duration: "00:40:52",
    publishDate: "2024-07-31",
    youtubeId: "qg_mtsagK44",
    channel: "FusionHaa Podcast",
    channelUrl: "https://www.youtube.com/@fusionhaapodcast",
    tags: ["FusionHaa", "Blue Lock", "English Dub", "Voice Actors", "Interview"],
    language: "en",
  },
  {
    id: "bt-cristina-vee",
    title: "Cristina Vee — Community, Anxiety & 10 Years of Miraculous",
    description: "Cristina Vee (Homura from Madoka Magica, Sailor Mars, Darkness from KonoSuba, Ladybug) opens up about mental health, breaking into voice acting, and 10 years of Miraculous.",
    duration: "00:43:35",
    publishDate: "2026-02-04",
    youtubeId: "xXaghXgLQx0",
    channel: "Beneath the Tangles",
    channelUrl: "https://www.youtube.com/@BeneathTheTangles",
    tags: ["Something Genuine", "Cristina Vee", "Voice Acting", "Mental Health", "Miraculous"],
    language: "en",
  },
  {
    id: "fx-jinwoo-improv",
    title: "Sung Jinwoo's Voice Actor On Improvised Lines — Solo Leveling",
    description: "Aleks Le, the English voice of Sung Jinwoo, talks about his favorite improvised lines in Solo Leveling including the iconic 'Wakey Wakey' scene at FanX Comic Con.",
    duration: "00:08:00",
    publishDate: "2026-05-16",
    youtubeId: "l7b9dx0YyNU",
    channel: "FanX Comic Conventions",
    channelUrl: "https://www.youtube.com/@FanXConvention",
    tags: ["Solo Leveling", "Aleks Le", "Voice Acting", "FanX", "Improv"],
    language: "en",
  },
  {
    id: "cr-va-lesson",
    title: "Solo Leveling Voice Acting Lesson — Aleks Le Teaches Vinnie Hacker & Nicewigg",
    description: "Aleks Le (voice of Sung Jinwoo) gives voice acting lessons to Vinnie Hacker and Nicewigg on Crunchyroll. A fun look at what it takes to be an anime voice actor.",
    duration: "00:12:00",
    publishDate: "2025-03-14",
    youtubeId: "IiLN_nJF1rA",
    channel: "Crunchyroll",
    channelUrl: "https://www.youtube.com/@Crunchyroll",
    tags: ["Crunchyroll", "Solo Leveling", "Voice Acting", "Aleks Le", "Lesson"],
    language: "en",
  },
  {
    id: "tf-rengoku",
    title: "What Gave Rengoku His Iconic Voice — Demon Slayer",
    description: "A deep dive into how Noshir Dalal brought Rengoku to life in Demon Slayer. Musical theater training, breath control, and the casting magic behind the Flame Hashira.",
    duration: "00:10:00",
    publishDate: "2026-01-15",
    youtubeId: "TUVpuMrbvL4",
    channel: "Timothy Flick",
    channelUrl: "https://www.youtube.com/@TimothyFlick",
    tags: ["Demon Slayer", "Rengoku", "Voice Acting", "Behind the Scenes"],
    language: "en",
  },
  {
    id: "dt-prozd",
    title: "Sungwon Cho (ProZD) Interview — Voice Acting to Live Action",
    description: "Sungwon Cho (ProZD) discusses transitioning from voice acting to live action, his roles in God of War Ragnarok, Anime Crimes Division, and the upcoming Blackberry film.",
    duration: "00:35:00",
    publishDate: "2026-03-20",
    youtubeId: "2m_v6JZR-d4",
    channel: "Double Toasted Interviews",
    channelUrl: "https://www.youtube.com/@DoubleToastedInterviews",
    tags: ["ProZD", "Sungwon Cho", "Voice Acting", "Interview", "God of War"],
    language: "en",
  },
  {
    id: "tmms-parigna",
    title: "How Parigna Pandya Shah Got Started in Voice Acting",
    description: "Parigna Pandya Shah shares her journey from Gujarati films to voice acting — how she discovered her talent for diction and landed her first dubbing role.",
    duration: "00:03:00",
    publishDate: "2026-04-10",
    youtubeId: "TxcNAxoWozk",
    channel: "The MotorMouth Show",
    channelUrl: "https://www.youtube.com/@Motormouth",
    tags: ["MotorMouth", "Voice Acting", "Hindi", "Origin Story", "Dubbing"],
    language: "hi",
  },
];
