export interface TheatricalRelease {
  id: string;
  mal_id: number;
  title: string;
  displayTitle: string;
  image: string;
  synopsis: string;
  genres: string[];
  releaseDate: string;
  releaseYear: number;
  distributor: string;
  languages: string[];
  boxOfficeIndia?: string;
  boxOfficeWorldwide?: string;
  budget?: string;
  rating: string;
  screenCount?: number;
  status: "released" | "upcoming" | "limited";
  imdbUrl?: string;
  wikipediaUrl?: string;
  posterUrl?: string;
  trailerUrl?: string;
  reviewScore?: number;
  reviewCount?: number;
  malUrl?: string;
}

export const THEATRICAL_RELEASES: TheatricalRelease[] = [
  // ══════════════════════════════════════════════
  // 2026 RELEASES (India)
  // ══════════════════════════════════════════════
  {
    id: "attack-on-titan-last-attack-2026",
    mal_id: 56710,
    title: "Attack on Titan: The Last Attack",
    displayTitle: "Attack on Titan: The Last Attack",
    image: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    synopsis: "A theatrical compilation combining The Final Chapters Special 1 & 2 into a single cinematic experience, with a new post-credits scene based on Attack on School Castes.",
    genres: ["Action", "Drama", "Fantasy", "Shounen"],
    releaseDate: "2026-07-24",
    releaseYear: 2026,
    distributor: "Medialink, PVR Inox Pictures",
    languages: ["Japanese (English Sub)"],
    rating: "UA",
    screenCount: 500,
    status: "upcoming",
    malUrl: "https://myanimelist.net/anime/56710",
  },
  {
    id: "jujutsu-kaisen-hidden-inventory-2026",
    mal_id: 56172,
    title: "Jujutsu Kaisen: Hidden Inventory / Premature Death",
    displayTitle: "Jujutsu Kaisen: Hidden Inventory / Premature Death",
    image: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    synopsis: "A theatrical compilation adapting the Hidden Inventory / Premature Death arc, bringing together the first five episodes of Season 2 into a single theatrical feature.",
    genres: ["Action", "Fantasy", "Supernatural"],
    releaseDate: "2026-01-01",
    releaseYear: 2026,
    distributor: "Medialink, PVR Inox Pictures",
    languages: ["Japanese (English Sub)"],
    boxOfficeIndia: "₹4.63 Crore",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/56172",
  },
  {
    id: "scarlet-2026",
    mal_id: 58435,
    title: "Scarlet",
    displayTitle: "Scarlet",
    image: "https://cdn.myanimelist.net/images/anime/1781/150871.jpg",
    synopsis: "A medieval princess gains the ability to travel across time and space to avenge her father's death. Written and directed by Mamoru Hosoda, loosely inspired by Shakespeare's Hamlet.",
    genres: ["Adventure", "Drama", "Fantasy"],
    releaseDate: "2026-02-06",
    releaseYear: 2026,
    distributor: "Crunchyroll, Sony Pictures India",
    languages: ["Japanese (English Sub)"],
    boxOfficeIndia: "₹49 Lakh",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/58435",
  },
  {
    id: "jujutsu-kaisen-execution-2026",
    mal_id: 58391,
    title: "Jujutsu Kaisen: Execution (Shibuya Incident x The Culling Game)",
    displayTitle: "Jujutsu Kaisen: Execution",
    image: "https://cdn.myanimelist.net/images/anime/1438/154138.jpg",
    synopsis: "A special edition combining the Shibuya Incident arc with a preview of the Culling Game arc, bridging the second season and the upcoming continuation.",
    genres: ["Action", "Fantasy", "Supernatural"],
    releaseDate: "2026-02-27",
    releaseYear: 2026,
    distributor: "Medialink, PVR Inox Pictures",
    languages: ["Japanese (English Sub)"],
    boxOfficeIndia: "₹36 Lakh",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/58391",
  },

  // ══════════════════════════════════════════════
  // 2026 UPCOMING (India)
  // ══════════════════════════════════════════════
  {
    id: "chao-2026",
    mal_id: 60000,
    title: "Chao",
    displayTitle: "Chao",
    image: "https://cdn.myanimelist.net/images/anime/1704/150419.jpg",
    synopsis: "An upcoming animated film set to release in Indian theatres.",
    genres: ["Adventure", "Fantasy"],
    releaseDate: "2026-08-07",
    releaseYear: 2026,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (English Sub)"],
    rating: "UA",
    status: "upcoming",
    malUrl: "https://myanimelist.net/anime/60000",
  },
  {
    id: "doraemon-castle-undersea-2026",
    mal_id: 60200,
    title: "Doraemon: New Nobita and the Castle of the Undersea Devil",
    displayTitle: "Doraemon: Castle of the Undersea Devil",
    image: "https://cdn.myanimelist.net/images/anime/1646/153726.jpg",
    synopsis: "Nobita and Doraemon dive deep under the sea to explore a mysterious underwater castle in this new Doraemon theatrical adventure.",
    genres: ["Adventure", "Comedy", "Fantasy", "Kids"],
    releaseDate: "2026-10-02",
    releaseYear: 2026,
    distributor: "Disney India",
    languages: ["Hindi", "Tamil", "Telugu"],
    rating: "U",
    status: "upcoming",
  },
  {
    id: "slime-movie-azure-sea-2026",
    mal_id: 59419,
    title: "That Time I Got Reincarnated as a Slime the Movie: Tears of the Azure Sea",
    displayTitle: "Slime Movie: Tears of the Azure Sea",
    image: "https://cdn.myanimelist.net/images/anime/1447/153665.jpg",
    synopsis: "A brand-new original story set in the world of Slime, continuing Rimuru's journey. Written and supervised by series creator Fuse.",
    genres: ["Action", "Adventure", "Fantasy"],
    releaseDate: "2026-12-01",
    releaseYear: 2026,
    distributor: "Muse Communication",
    languages: ["Japanese (English Sub)"],
    rating: "UA",
    status: "upcoming",
    malUrl: "https://myanimelist.net/anime/59419",
  },

  // ══════════════════════════════════════════════
  // 2025 RELEASES (India)
  // ══════════════════════════════════════════════
  {
    id: "demon-slayer-infinity-castle-india-2025",
    mal_id: 56710,
    title: "Demon Slayer: Kimetsu no Yaiba – The Movie: Infinity Castle",
    displayTitle: "Demon Slayer: Infinity Castle",
    image: "https://cdn.myanimelist.net/images/anime/1681/148216.jpg",
    synopsis: "The climactic finale begins as Tanjiro and the Hashira enter the Infinity Castle for an all-out battle against Muzan Kibutsuji. The highest-grossing anime film in Indian history.",
    genres: ["Action", "Fantasy", "Shounen"],
    releaseDate: "2025-09-12",
    releaseYear: 2025,
    distributor: "Crunchyroll, Sony Pictures India",
    languages: ["Japanese", "English", "Hindi", "Tamil", "Telugu"],
    boxOfficeIndia: "₹90.09 Crore",
    boxOfficeWorldwide: "$674M",
    rating: "UA",
    screenCount: 1700,
    status: "released",
    trailerUrl: "https://www.youtube.com/watch?v=oKnwWm3aiHc",
    malUrl: "https://myanimelist.net/anime/56710",
  },
  {
    id: "shinchan-dinosaur-diary-india-2025",
    mal_id: 55620,
    title: "Shinchan: Our Dinosaur Diary",
    displayTitle: "Shinchan: Our Dinosaur Diary",
    image: "https://cdn.myanimelist.net/images/anime/1882/150076.jpg",
    synopsis: "Shinchan and his family discover a mysterious dinosaur egg, leading to an exciting prehistoric adventure. The franchise's return to Indian theatres after 14 years.",
    genres: ["Comedy", "Kids", "Adventure"],
    releaseDate: "2025-05-09",
    releaseYear: 2025,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese", "Hindi", "Tamil", "Telugu"],
    boxOfficeIndia: "₹9.83 Crore",
    rating: "U",
    screenCount: 300,
    status: "released",
    malUrl: "https://myanimelist.net/anime/55620",
  },
  {
    id: "shinchan-kasukabe-dancers-india-2025",
    mal_id: 58268,
    title: "Shin-chan: The Spicy Kasukabe Dancers in India",
    displayTitle: "Shin-chan: Kasukabe Dancers in India",
    image: "https://cdn.myanimelist.net/images/anime/1955/150272.jpg",
    synopsis: "The Kasukabe Defense Force takes their dance to India in this theatrical adventure set primarily in the Indian subcontinent.",
    genres: ["Comedy", "Kids", "Adventure"],
    releaseDate: "2025-09-26",
    releaseYear: 2025,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese", "Hindi", "Tamil", "Telugu"],
    boxOfficeIndia: "₹5 Crore",
    rating: "U",
    status: "released",
    malUrl: "https://myanimelist.net/anime/58268",
  },
  {
    id: "chainsaw-man-reze-arc-india-2025",
    mal_id: 56696,
    title: "Chainsaw Man – The Movie: Reze Arc",
    displayTitle: "Chainsaw Man: Reze Arc",
    image: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    synopsis: "Denji meets Reze, a girl with a dangerous secret. The first A-rated anime film to receive a theatrical release in India.",
    genres: ["Action", "Fantasy", "Horror", "Romance"],
    releaseDate: "2025-09-26",
    releaseYear: 2025,
    distributor: "Crunchyroll, Sony Pictures India",
    languages: ["Japanese", "Hindi"],
    boxOfficeIndia: "₹4.8 Crore",
    rating: "A",
    status: "released",
    malUrl: "https://myanimelist.net/anime/56696",
  },
  {
    id: "ramayana-legend-prince-rama-2025",
    mal_id: 32281,
    title: "Ramayana: The Legend of Prince Rama [4K Remaster]",
    displayTitle: "Ramayana: Legend of Prince Rama (4K)",
    image: "https://cdn.myanimelist.net/images/anime/1208/94745.jpg",
    malUrl: "https://myanimelist.net/anime/32281",
    synopsis: "The Japan-India co-produced animated adaptation of the epic Ramayana, remastered in 4K. A cult classic receiving its first-ever wide theatrical release in India.",
    genres: ["Action", "Drama", "Fantasy", "Historical"],
    releaseDate: "2025-01-24",
    releaseYear: 2025,
    distributor: "Geek Pictures",
    languages: ["English", "Hindi", "Tamil", "Telugu"],
    boxOfficeIndia: "₹4.6 Crore",
    rating: "U",
    screenCount: 620,
    status: "released",
  },
  {
    id: "solo-leveling-reawakening-india-2024",
    mal_id: 56950,
    title: "Solo Leveling – ReAwakening",
    displayTitle: "Solo Leveling: ReAwakening",
    image: "https://cdn.myanimelist.net/images/anime/1983/146190.jpg",
    synopsis: "A compilation film condensing Season 1 with the first two episodes of Season 2 as a special preview. Sung Jin-Woo's journey from the weakest hunter to the dominant force.",
    genres: ["Action", "Adventure", "Fantasy"],
    releaseDate: "2024-12-04",
    releaseYear: 2024,
    distributor: "Crunchyroll, Sony Pictures India",
    languages: ["Japanese", "English", "Hindi"],
    boxOfficeIndia: "₹2.29 Crore",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/56950",
  },
  {
    id: "haikyu-dumpster-battle-india-2024",
    mal_id: 52781,
    title: "Haikyu!! The Dumpster Battle",
    displayTitle: "Haikyu!! The Dumpster Battle",
    image: "https://cdn.myanimelist.net/images/anime/1665/140360.jpg",
    synopsis: "Karasuno High vs. Nekoma High in the long-awaited showdown. One of the highest-grossing anime titles of 2024 in India.",
    genres: ["Sports", "Drama", "Shounen"],
    releaseDate: "2024-05-31",
    releaseYear: 2024,
    distributor: "PVR Inox Pictures, Medialink",
    languages: ["Japanese (English Sub)"],
    boxOfficeIndia: "₹5.04 Crore",
    rating: "UA",
    screenCount: 200,
    status: "released",
    malUrl: "https://myanimelist.net/anime/52781",
  },
  {
    id: "boy-and-the-heron-india-2024",
    mal_id: 43608,
    title: "The Boy and the Heron",
    displayTitle: "The Boy and the Heron",
    image: "https://cdn.myanimelist.net/images/anime/1126/139654.jpg",
    synopsis: "From Hayao Miyazaki and Studio Ghibli. A deeply personal fantasy drama following a boy's journey into a magical realm. Winner of the Academy Award for Best Animated Feature.",
    genres: ["Adventure", "Drama", "Fantasy"],
    releaseDate: "2024-05-10",
    releaseYear: 2024,
    distributor: "Warner Bros. India, Encore Films",
    languages: ["Japanese", "English"],
    boxOfficeIndia: "₹3.05 Crore",
    rating: "UA",
    screenCount: 209,
    status: "released",
    malUrl: "https://myanimelist.net/anime/43608",
  },
  {
    id: "lord-of-rings-rohirrim-india-2024",
    mal_id: 57506,
    title: "The Lord of the Rings: The War of the Rohirrim",
    displayTitle: "LOTR: War of the Rohirrim",
    image: "https://cdn.myanimelist.net/images/anime/1587/142014.jpg",
    synopsis: "An animated prequel set nearly two centuries before The Two Towers, chronicling the heroic tale of Helm Hammerhand and the origins of Helm's Deep.",
    genres: ["Action", "Adventure", "Fantasy"],
    releaseDate: "2024-12-13",
    releaseYear: 2024,
    distributor: "Warner Bros. India",
    languages: ["English"],
    boxOfficeIndia: "₹84 Lakh",
    rating: "UA",
    status: "released",
  },
  {
    id: "spy-x-family-code-white-india-2024",
    mal_id: 56983,
    title: "Spy x Family Code: White",
    displayTitle: "Spy x Family Code: White",
    image: "https://cdn.myanimelist.net/images/anime/1426/139388.jpg",
    synopsis: "The Forger family goes on a culinary adventure that turns into a secret mission. Loid, Yor, and Anya's first theatrical adventure.",
    genres: ["Action", "Comedy", "Slice of Life"],
    releaseDate: "2024-07-19",
    releaseYear: 2024,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (English Sub)"],
    boxOfficeIndia: "₹33 Lakh",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/56983",
  },

  // ══════════════════════════════════════════════
  // CLASSIC / EARLIER RELEASES (India)
  // ══════════════════════════════════════════════
  {
    id: "demon-slayer-mugen-train-india",
    mal_id: 101922,
    title: "Demon Slayer: Kimetsu no Yaiba – The Movie: Mugen Train",
    displayTitle: "Demon Slayer: Mugen Train",
    image: "https://cdn.myanimelist.net/images/anime/1704/106947.jpg",
    synopsis: "Tanjiro and friends board the Mugen Train to investigate disappearances. The film that changed anime theatricals in India forever.",
    genres: ["Action", "Fantasy", "Shounen"],
    releaseDate: "2021-08-13",
    releaseYear: 2021,
    distributor: "Crunchyroll, Sony Pictures India",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹15.60 Crore",
    boxOfficeWorldwide: "$503.1M",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/101922",
  },
  {
    id: "jujutsu-kaisen-0-india",
    mal_id: 44347,
    title: "Jujutsu Kaisen 0",
    displayTitle: "Jujutsu Kaisen 0",
    image: "https://cdn.myanimelist.net/images/anime/1121/119044.jpg",
    synopsis: "Yuta Okkotsu enrolls in Jujutsu High to control his cursed spirit. The prequel that started it all on the Indian big screen.",
    genres: ["Action", "Fantasy", "School", "Supernatural"],
    releaseDate: "2022-04-01",
    releaseYear: 2022,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹9.80 Crore",
    boxOfficeWorldwide: "$196.2M",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/44347",
  },
  {
    id: "suzume-india",
    mal_id: 52522,
    title: "Suzume no Tojimari",
    displayTitle: "Suzume",
    image: "https://cdn.myanimelist.net/images/anime/1598/128450.jpg",
    synopsis: "A girl journeys across Japan to close magical doors linked to natural disasters. Once the highest-grossing anime film in India before Infinity Castle.",
    genres: ["Adventure", "Drama", "Fantasy", "Romance"],
    releaseDate: "2023-04-21",
    releaseYear: 2023,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹10 Crore",
    boxOfficeWorldwide: "$327.6M",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/52522",
  },
  {
    id: "one-piece-film-red-india",
    mal_id: 107937,
    title: "One Piece Film: Red",
    displayTitle: "One Piece Film: Red",
    image: "https://cdn.myanimelist.net/images/anime/1668/125323.jpg",
    synopsis: "Luffy and the Straw Hats encounter Uta, a singer with a mysterious power connected to Shanks.",
    genres: ["Action", "Adventure", "Fantasy", "Music"],
    releaseDate: "2022-10-28",
    releaseYear: 2022,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹14.20 Crore",
    boxOfficeWorldwide: "$208.4M",
    rating: "UA",
    status: "released",
    malUrl: "https://myanimelist.net/anime/107937",
  },
  {
    id: "your-name-india",
    mal_id: 32281,
    title: "Kimi no Na wa.",
    displayTitle: "Your Name",
    image: "https://cdn.myanimelist.net/images/anime/5/87048.jpg",
    synopsis: "Two strangers discover they are swapping bodies across time and space. Makoto Shinkai's masterpiece that opened doors for anime in India.",
    genres: ["Drama", "Romance", "Supernatural"],
    releaseDate: "2017-06-09",
    releaseYear: 2017,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (Hindi Sub)"],
    boxOfficeWorldwide: "$380.2M",
    rating: "U",
    status: "released",
    malUrl: "https://myanimelist.net/anime/32281",
  },
  {
    id: "weathering-with-you-india",
    mal_id: 103702,
    title: "Tenki no Ko",
    displayTitle: "Weathering with You",
    image: "https://cdn.myanimelist.net/images/anime/1880/101146.jpg",
    synopsis: "A boy runs away to Tokyo and befriends a girl who can control the weather. Makoto Shinkai's follow-up to Your Name.",
    genres: ["Drama", "Fantasy", "Romance"],
    releaseDate: "2019-10-11",
    releaseYear: 2019,
    distributor: "PVR Inox Pictures",
    languages: ["Japanese (Hindi Sub)"],
    boxOfficeWorldwide: "$193.3M",
    rating: "U",
    status: "released",
    malUrl: "https://myanimelist.net/anime/103702",
  },
];

function parseBoxOfficeToCrore(value?: string): number {
  if (!value) return 0;
  const num = parseFloat(value.replace(/[₹,\s]/g, ""));
  if (value.includes("Lakh")) return num / 100;
  if (value.includes("Crore")) return num;
  return num;
}

export const THEATRICAL_STATS = {
  totalReleases: THEATRICAL_RELEASES.length,
  releasedInIndia: THEATRICAL_RELEASES.filter(r => r.status === "released").length,
  upcomingReleases: THEATRICAL_RELEASES.filter(r => r.status === "upcoming").length,
  topBoxOffice: THEATRICAL_RELEASES
    .filter(r => r.boxOfficeIndia)
    .sort((a, b) => parseBoxOfficeToCrore(b.boxOfficeIndia) - parseBoxOfficeToCrore(a.boxOfficeIndia))
    .slice(0, 5),
  distributors: [
    "Crunchyroll, Sony Pictures India",
    "Medialink, PVR Inox Pictures",
    "PVR Inox Pictures",
    "Warner Bros. India",
    "Muse Communication",
    "Geek Pictures",
  ],
  lastUpdated: "2026-07-25",
} as const;
