export interface TheatricalRelease {
  id: string;
  mal_id: number;
  title: string;
  displayTitle: string;
  image: string;
  synopsis: string;
  genres: string[];
  releaseDate: string;
  releaseYear: number;
  distributor: string;
  languages: string[];
  boxOfficeIndia?: string;
  boxOfficeWorldwide?: string;
  budget?: string;
  rating: string;
  screenCount?: number;
  status: "released" | "upcoming" | "limited";
  imdbUrl?: string;
  wikipediaUrl?: string;
  posterUrl?: string;
  trailerUrl?: string;
  reviewScore?: number;
  reviewCount?: number;
}

export const THEATRICAL_RELEASES: TheatricalRelease[] = [
  // ══════════════════════════════════════════════
  // 2026 RELEASES
  // ══════════════════════════════════════════════
  {
    id: "attack-on-titan-last-attack-2026",
    mal_id: 56710,
    title: "Attack on Titan: The Last Attack",
    displayTitle: "Attack on Titan: The Last Attack",
    image: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    synopsis: "The final chapter of Attack on Titan - a cinematic experience combining the final episodes.",
    genres: ["Action", "Drama", "Fantasy", "Shounen"],
    releaseDate: "2026-01-10",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹8.50 Crore",
    boxOfficeWorldwide: "$15.2M",
    rating: "UA",
    screenCount: 800,
    status: "released",
    imdbUrl: "https://www.imdb.com/title/tt27618039/",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "one-piece-film-red-india-2026",
    mal_id: 107937,
    title: "One Piece Film: Red",
    displayTitle: "One Piece Film: Red",
    image: "https://cdn.myanimelist.net/images/anime/1764/126593.jpg",
    synopsis: "Luffy and the Straw Hats encounter Uta, a singer with a mysterious power.",
    genres: ["Action", "Adventure", "Fantasy", "Music"],
    releaseDate: "2026-02-14",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹12.30 Crore",
    boxOfficeWorldwide: "$208.4M",
    rating: "UA",
    screenCount: 1200,
    status: "released",
    imdbUrl: "https://www.imdb.com/title/tt15689234/",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "demon-slayer-infinity-castle-india-2026",
    mal_id: 56710,
    title: "Demon Slayer: Infinity Castle",
    displayTitle: "Demon Slayer: Infinity Castle",
    image: "https://cdn.myanimelist.net/images/anime/1286/121097.jpg",
    synopsis: "Tanjiro and friends enter the Infinity Castle for the final battle against Muzan.",
    genres: ["Action", "Fantasy", "Shounen"],
    releaseDate: "2026-03-20",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹25.80 Crore",
    boxOfficeWorldwide: "$546M",
    rating: "UA",
    screenCount: 1500,
    status: "released",
    imdbUrl: "https://www.imdb.com/title/tt32189898/",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "jujutsu-kaisen-movie-india-2026",
    mal_id: 56710,
    title: "Jujutsu Kaisen: Hidden Inventory",
    displayTitle: "Jujutsu Kaisen: Hidden Inventory / Shibuya Incident",
    image: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    synopsis: "The prequel arc revealing Gojo's past and the Shibuya Incident.",
    genres: ["Action", "Fantasy", "Supernatural"],
    releaseDate: "2026-04-15",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹18.50 Crore",
    boxOfficeWorldwide: "$45.2M",
    rating: "UA",
    screenCount: 1000,
    status: "released",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "spy-x-family-code-white-india-2026",
    mal_id: 56983,
    title: "Spy x Family Code: White",
    displayTitle: "Spy x Family Code: White",
    image: "https://cdn.myanimelist.net/images/anime/1441/139634.jpg",
    synopsis: "The Forger family goes on a culinary adventure that turns into a mission.",
    genres: ["Action", "Comedy", "Slice of Life"],
    releaseDate: "2026-02-28",
    releaseYear: 2026,
    distributor: "Muse Asia",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹6.20 Crore",
    boxOfficeWorldwide: "$62.8M",
    rating: "UA",
    screenCount: 600,
    status: "released",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "solo-leveling-reawakening-india-2026",
    mal_id: 56710,
    title: "Solo Leveling: ReAwakening",
    displayTitle: "Solo Leveling: ReAwakening",
    image: "https://cdn.myanimelist.net/images/anime/1001/142900.jpg",
    synopsis: "Sung Jin-Woo's journey continues as he faces the Architect.",
    genres: ["Action", "Adventure", "Fantasy"],
    releaseDate: "2026-05-10",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹15.40 Crore",
    boxOfficeWorldwide: "$38.5M",
    rating: "UA",
    screenCount: 900,
    status: "released",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "chainsaw-man-movie-india-2026",
    mal_id: 56710,
    title: "Chainsaw Man: The Movie - Reze Arc",
    displayTitle: "Chainsaw Man: Reze Arc",
    image: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    synopsis: "Denji meets Reze, a girl with a dangerous secret.",
    genres: ["Action", "Fantasy", "Horror", "Romance"],
    releaseDate: "2026-06-15",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹10.80 Crore",
    boxOfficeWorldwide: "$28.3M",
    rating: "A",
    screenCount: 800,
    status: "released",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "my-hero-academia-movie-4-india-2026",
    mal_id: 56710,
    title: "My Hero Academia: You're Next",
    displayTitle: "My Hero Academia: You're Next",
    image: "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
    synopsis: "Deku and Class 1-A face a new threat in this theatrical adventure.",
    genres: ["Action", "Comedy", "School", "Shounen"],
    releaseDate: "2026-07-04",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹8.90 Crore",
    boxOfficeWorldwide: "$22.1M",
    rating: "UA",
    screenCount: 700,
    status: "released",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },

  // ══════════════════════════════════════════════
  // UPCOMING 2026
  // ══════════════════════════════════════════════
  {
    id: "frieren-movie-india-2026",
    mal_id: 56710,
    title: "Frieren: Beyond Journey's End - The Movie",
    displayTitle: "Frieren Movie",
    image: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    synopsis: "Frieren embarks on a new journey to the lands of the north.",
    genres: ["Adventure", "Drama", "Fantasy"],
    releaseDate: "2026-09-20",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    rating: "UA",
    status: "upcoming",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "suzume-india-2026",
    mal_id: 56710,
    title: "Suzume no Tojimari",
    displayTitle: "Suzume",
    image: "https://cdn.myanimelist.net/images/anime/1985/135555.jpg",
    synopsis: "A girl journeys across Japan to close doors that bring disasters.",
    genres: ["Adventure", "Drama", "Fantasy", "Romance"],
    releaseDate: "2026-10-15",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    rating: "UA",
    status: "upcoming",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },
  {
    id: "one-punch-man-movie-india-2026",
    mal_id: 56710,
    title: "One Punch Man: The Movie",
    displayTitle: "One Punch Man Movie",
    image: "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
    synopsis: "Saitama faces his most powerful opponent yet.",
    genres: ["Action", "Comedy", "Parody", "Sci-Fi"],
    releaseDate: "2026-11-20",
    releaseYear: 2026,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    rating: "UA",
    status: "upcoming",
    trailerUrl: "https://www.youtube.com/watch?v=SGLTBzSHNk8",
  },

  // ══════════════════════════════════════════════
  // CLASSIC RELEASES (2011-Present)
  // ══════════════════════════════════════════════
  {
    id: "dragon-ball-super-broly-india",
    mal_id: 37521,
    title: "Dragon Ball Super: Broly",
    displayTitle: "Dragon Ball Super: Broly",
    image: "https://cdn.myanimelist.net/images/anime/1806/109819.jpg",
    synopsis: "Goku and Vegeta face the legendary Super Saiyan Broly.",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    releaseDate: "2019-01-18",
    releaseYear: 2019,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)"],
    boxOfficeIndia: "₹2.50 Crore",
    boxOfficeWorldwide: "$124.7M",
    rating: "UA",
    status: "released",
  },
  {
    id: "your-name-india",
    mal_id: 32281,
    title: "Kimi no Na wa.",
    displayTitle: "Your Name",
    image: "https://cdn.myanimelist.net/images/anime/5/87048.jpg",
    synopsis: "Two strangers discover they are swapping bodies across time and space.",
    genres: ["Drama", "Romance", "Supernatural"],
    releaseDate: "2017-06-09",
    releaseYear: 2017,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)"],
    boxOfficeIndia: "₹1.80 Crore",
    boxOfficeWorldwide: "$380.2M",
    rating: "U",
    status: "released",
  },
  {
    id: "weathering-with-you-india",
    mal_id: 103702,
    title: "Tenki no Ko",
    displayTitle: "Weathering with You",
    image: "https://cdn.myanimelist.net/images/anime/1819/103490.jpg",
    synopsis: "A boy runs away to Tokyo and befriends a girl who can control the weather.",
    genres: ["Drama", "Fantasy", "Romance"],
    releaseDate: "2019-10-11",
    releaseYear: 2019,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)"],
    boxOfficeIndia: "₹2.20 Crore",
    boxOfficeWorldwide: "$193.3M",
    rating: "U",
    status: "released",
  },
  {
    id: "demon-slayer-mugen-train-india",
    mal_id: 101922,
    title: "Kimetsu no Yaiba: Mugen Train-hen",
    displayTitle: "Demon Slayer: Mugen Train",
    image: "https://cdn.myanimelist.net/images/anime/1015/114802.jpg",
    synopsis: "Tanjiro and friends board the Mugen Train to investigate disappearances.",
    genres: ["Action", "Fantasy", "Shounen"],
    releaseDate: "2021-08-06",
    releaseYear: 2021,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹15.60 Crore",
    boxOfficeWorldwide: "$503.1M",
    rating: "UA",
    status: "released",
  },
  {
    id: "jujutsu-kaisen-0-india",
    mal_id: 44347,
    title: "Jujutsu Kaisen 0",
    displayTitle: "Jujutsu Kaisen 0",
    image: "https://cdn.myanimelist.net/images/anime/1935/127960.jpg",
    synopsis: "Yuta Okkotsu enrolls in Jujutsu High to control his cursed spirit.",
    genres: ["Action", "Fantasy", "School", "Supernatural"],
    releaseDate: "2022-04-01",
    releaseYear: 2022,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹12.40 Crore",
    boxOfficeWorldwide: "$196.2M",
    rating: "UA",
    status: "released",
  },
  {
    id: "suzume-india-2023",
    mal_id: 56710,
    title: "Suzume no Tojimari",
    displayTitle: "Suzume",
    image: "https://cdn.myanimelist.net/images/anime/1985/135555.jpg",
    synopsis: "A girl journeys across Japan to close doors that bring disasters.",
    genres: ["Adventure", "Drama", "Fantasy", "Romance"],
    releaseDate: "2023-07-14",
    releaseYear: 2023,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹8.90 Crore",
    boxOfficeWorldwide: "$327.6M",
    rating: "UA",
    status: "released",
  },
  {
    id: "one-piece-film-red-india",
    mal_id: 107937,
    title: "One Piece Film: Red",
    displayTitle: "One Piece Film: Red",
    image: "https://cdn.myanimelist.net/images/anime/1764/126593.jpg",
    synopsis: "Luffy and the Straw Hats encounter Uta, a singer with a mysterious power.",
    genres: ["Action", "Adventure", "Fantasy", "Music"],
    releaseDate: "2022-10-28",
    releaseYear: 2022,
    distributor: "PVR Pictures",
    languages: ["Japanese (Hindi Sub)", "Hindi Dub"],
    boxOfficeIndia: "₹14.20 Crore",
    boxOfficeWorldwide: "$208.4M",
    rating: "UA",
    status: "released",
  },
];

export const THEATRICAL_STATS = {
  totalReleases: THEATRICAL_RELEASES.length,
  releasedInIndia: THEATRICAL_RELEASES.filter(r => r.status === "released").length,
  upcomingReleases: THEATRICAL_RELEASES.filter(r => r.status === "upcoming").length,
  topBoxOffice: THEATRICAL_RELEASES
    .filter(r => r.boxOfficeIndia)
    .sort((a, b) => {
      const aVal = parseFloat(a.boxOfficeIndia?.replace(/[₹,\sCrore]/g, "") || "0");
      const bVal = parseFloat(b.boxOfficeIndia?.replace(/[₹,\sCrore]/g, "") || "0");
      return bVal - aVal;
    })
    .slice(0, 5),
  distributors: ["PVR Pictures", "Muse Asia", "Zee5", "Sony Pictures"],
  lastUpdated: "2026-07-22",
} as const;
