export interface CartoonEntry {
  id: string;
  title: string;
  displayTitle: string;
  image: string;
  synopsis: string;
  genres: string[];
  network: string;
  language: string[];
  country: string;
  totalEpisodes?: number;
  seasons?: number;
  status: "airing" | "completed" | "hiatus";
  releaseYear: number;
  endYear?: number;
  rating: string;
  creator?: string;
  studio?: string;
  dubPlatform?: string;
  description: string;
  tags: string[];
  popularity?: "high" | "medium" | "low";
}

export const TOONS_DATABASE: CartoonEntry[] = [
  // ══════════════════════════════════════════════
  // INDIAN ORIGINAL CARTOONS
  // ══════════════════════════════════════════════
  {
    id: "chhota-bheem",
    title: "Chhota Bheem",
    displayTitle: "Chhota Bheem",
    image: "",
    synopsis: "A strong young boy protects the village of Dholakpur from various threats.",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    network: "Green Gold Animation",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "India",
    totalEpisodes: 600,
    seasons: 12,
    status: "airing",
    releaseYear: 2008,
    rating: "U",
    creator: "Rajiv Chilaka",
    studio: "Green Gold Animation",
    description: "Chhota Bheem is one of India's most popular animated characters. The series follows Bheem, a strong and kind-hearted boy, and his friends as they protect the kingdom of Dholakpur.",
    tags: ["Indian", "Kids", "Action", "Comedy", "Popular"],
    popularity: "high",
  },
  {
    id: "motu-patlu",
    title: "Motu Patlu",
    displayTitle: "Motu Patlu",
    image: "",
    synopsis: "Two best friends, Motu and Patlu, get into various comedic adventures in Furfuri Nagar.",
    genres: ["Comedy", "Slice of Life"],
    network: "Nickelodeon India",
    language: ["Hindi", "Tamil", "Telugu"],
    country: "India",
    totalEpisodes: 400,
    seasons: 8,
    status: "airing",
    releaseYear: 2012,
    rating: "U",
    creator: "Niraj Vikram",
    studio: "Cosmos-Maya",
    description: "Motu Patlu is a popular Indian animated comedy series featuring two best friends - Motu, a fat man who loves samosas, and Patlu, a thin and intelligent man.",
    tags: ["Indian", "Kids", "Comedy", "Popular"],
    popularity: "high",
  },
  {
    id: "vir-the-kartoon-kid",
    title: "Vir: The Kartoon Kid",
    displayTitle: "Vir The Kartoon Kid",
    image: "",
    synopsis: "A young superhero kid saves the world with his friends.",
    genres: ["Action", "Comedy", "Sci-Fi"],
    network: "Sonic Nickelodeon",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 150,
    seasons: 3,
    status: "completed",
    releaseYear: 2016,
    rating: "U",
    studio: "Cosmos-Maya",
    description: "Vir The Kartoon Kid follows a young superhero who uses his gadgets and powers to save the world from villains with the help of his friends.",
    tags: ["Indian", "Kids", "Action", "Comedy"],
    popularity: "medium",
  },
  {
    id: "fishu-bhaiyya",
    title: "Fishu Bhaiyya",
    displayTitle: "Fishu Bhaiyya",
    image: "",
    synopsis: "A fish out of water comedy about a fish who lives among humans.",
    genres: ["Comedy", "Slice of Life"],
    network: "Sonic Nickelodeon",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 200,
    seasons: 4,
    status: "airing",
    releaseYear: 2020,
    rating: "U",
    studio: "Cosmos-Maya",
    description: "Fishu Bhaiyya is about a fish who somehow ends up living among humans and the hilarious situations that follow.",
    tags: ["Indian", "Kids", "Comedy"],
    popularity: "medium",
  },
  {
    id: "honey-bunny",
    displayTitle: "Honey Bunny Ka Jholmaal",
    title: "Honey Bunny Ka Jholmaal",
    image: "",
    synopsis: "Three cats and a dog cause chaos in a household.",
    genres: ["Comedy", "Slapstick"],
    network: "Sonic Nickelodeon",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 200,
    seasons: 4,
    status: "airing",
    releaseYear: 2018,
    rating: "U",
    studio: "Toonz Animation",
    description: "Honey Bunny Ka Jholmaal follows the hilarious misadventures of three cats and a dog living in the same household.",
    tags: ["Indian", "Kids", "Comedy"],
    popularity: "medium",
  },
  {
    id: "lambu-motu",
    title: "Lambu Motu Tingu Tong",
    displayTitle: "Lambu Motu Tingu Tong",
    image: "",
    synopsis: "The adventures of two friends - Lambu and Motu - in their village.",
    genres: ["Comedy", "Slice of Life"],
    network: "Sony YAY",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 100,
    seasons: 2,
    status: "completed",
    releaseYear: 2017,
    rating: "U",
    studio: "Cosmos-Maya",
    description: "Lambu Motu Tingu Tong is a comedy series about two friends and their funny adventures in a village setting.",
    tags: ["Indian", "Kids", "Comedy"],
    popularity: "low",
  },
  {
    id: "rudra",
    title: "Rudra: The Rise of the Black Sun",
    displayTitle: "Rudra",
    image: "",
    synopsis: "A young prince battles dark forces to save his kingdom.",
    genres: ["Action", "Adventure", "Fantasy"],
    network: "Amazon Prime Video",
    language: ["Hindi", "English"],
    country: "India",
    totalEpisodes: 26,
    seasons: 1,
    status: "completed",
    releaseYear: 2020,
    rating: "UA",
    studio: "Firefly Cartoon Studio",
    description: "Rudra follows a young prince who must battle dark forces and ancient evils to protect his kingdom from destruction.",
    tags: ["Indian", "Action", "Fantasy", "Adventure"],
    popularity: "medium",
  },
  {
    id: "kid-krishna",
    title: "Kid Krrish",
    displayTitle: "Kid Krrish",
    image: "",
    synopsis: "Young Krishna discovers his superhero powers and protects the city.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    network: "Discovery Kids India",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 52,
    seasons: 2,
    status: "completed",
    releaseYear: 2013,
    rating: "U",
    studio: "Turner International India",
    description: "Kid Krrish is about a young boy who discovers he has superpowers and uses them to protect the city from villains.",
    tags: ["Indian", "Kids", "Action", "Superhero"],
    popularity: "medium",
  },
  {
    id: "chhota-bheem-krrish",
    displayTitle: "Chhota Bheem Krrish",
    title: "Chhota Bheem Krrish",
    image: "",
    synopsis: "Chhota Bheem teams up with Krrish to save Dholakpur.",
    genres: ["Action", "Adventure", "Fantasy"],
    network: "Green Gold Animation",
    language: ["Hindi", "Tamil", "Telugu"],
    country: "India",
    totalEpisodes: 52,
    seasons: 2,
    status: "completed",
    releaseYear: 2019,
    rating: "U",
    studio: "Green Gold Animation",
    description: "Chhota Bheem Krrish is a crossover series where Bheem teams up with the superhero Krrish to protect Dholakpur from powerful villains.",
    tags: ["Indian", "Kids", "Action", "Superhero"],
    popularity: "medium",
  },

  // ══════════════════════════════════════════════
  // JAPANESE CARTOONS (HINDI DUB)
  // ══════════════════════════════════════════════
  {
    id: "doraemon",
    title: "Doraemon",
    displayTitle: "Doraemon",
    image: "",
    synopsis: "A robotic cat from the future helps a young boy with gadgets.",
    genres: ["Comedy", "Sci-Fi", "Slice of Life"],
    network: "JioHotstar",
    language: ["Hindi", "Tamil", "Telugu", "English", "Japanese"],
    country: "Japan",
    totalEpisodes: 1787,
    seasons: 25,
    status: "airing",
    releaseYear: 2005,
    rating: "U",
    studio: "Shin-Ei Animation",
    dubPlatform: "JioHotstar",
    description: "Doraemon is a Japanese manga and anime series about a robotic cat named Doraemon who travels back in time from the 22nd century to help Nobita Nobi with futuristic gadgets.",
    tags: ["Japanese", "Kids", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "shin-chan",
    title: "Shin-chan",
    displayTitle: "Crayon Shin-chan",
    image: "",
    synopsis: "A mischievous 5-year-old causes chaos wherever he goes.",
    genres: ["Comedy", "Slice of Life"],
    network: "JioHotstar",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "Japan",
    totalEpisodes: 1100,
    seasons: 20,
    status: "airing",
    releaseYear: 1992,
    rating: "U",
    studio: "Shin-Ei Animation",
    dubPlatform: "JioHotstar",
    description: "Crayon Shin-chan follows the adventures of Shinnosuke Nohara, a 5-year-old boy known for his inappropriate behavior and catchphrases.",
    tags: ["Japanese", "Kids", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "pokemon",
    title: "Pokemon",
    displayTitle: "Pokemon",
    image: "",
    synopsis: "Ash Ketchum travels the world catching and training Pokemon.",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "Japan",
    totalEpisodes: 1250,
    seasons: 25,
    status: "airing",
    releaseYear: 1997,
    rating: "U",
    studio: "OLM",
    dubPlatform: "Cartoon Network India",
    description: "Pokemon follows Ash Ketchum as he travels through various regions, catching and training Pokemon while striving to become a Pokemon Master.",
    tags: ["Japanese", "Kids", "Action", "Adventure", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "kochikame",
    title: "KochiKame",
    displayTitle: "Kochikame: Tokyo Beat Cops",
    image: "",
    synopsis: "A lazy police officer runs a side business from the police box.",
    genres: ["Comedy", "Slice of Life"],
    network: "JioHotstar",
    language: ["Hindi", "Japanese"],
    country: "Japan",
    totalEpisodes: 380,
    seasons: 8,
    status: "completed",
    releaseYear: 1996,
    rating: "U",
    studio: "Gallop",
    dubPlatform: "JioHotstar",
    description: "Kochikame follows the daily life of Kankichi Ryotsu, a lazy police officer who runs various side businesses from the police box.",
    tags: ["Japanese", "Kids", "Comedy", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "ninja-hattori",
    title: "Ninja Hattori",
    displayTitle: "Ninja Hattori",
    image: "",
    synopsis: "A young ninja helps his friend with everyday problems.",
    genres: ["Action", "Comedy", "Sci-Fi"],
    network: "JioHotstar",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "Japan",
    totalEpisodes: 520,
    seasons: 10,
    status: "completed",
    releaseYear: 1981,
    rating: "U",
    studio: "Shin-Ei Animation",
    dubPlatform: "JioHotstar",
    description: "Ninja Hattori follows the adventures of a young ninja named Hattori Kanzo who helps his friend Kenichi with everyday problems using his ninja skills.",
    tags: ["Japanese", "Kids", "Action", "Comedy", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "doraemon-nobita",
    title: "Doraemon: Nobita's Chronicles of the Moon Exploration",
    displayTitle: "Doraemon: Nobita's Moon Exploration",
    image: "",
    synopsis: "Nobita and friends explore the moon and discover a new civilization.",
    genres: ["Adventure", "Comedy", "Sci-Fi", "Fantasy"],
    network: "JioHotstar",
    language: ["Hindi", "Japanese"],
    country: "Japan",
    totalEpisodes: 1,
    seasons: 1,
    status: "completed",
    releaseYear: 2019,
    rating: "U",
    studio: "Shin-Ei Animation",
    dubPlatform: "JioHotstar",
    description: "Nobita and his friends discover a new civilization on the moon and embark on an incredible adventure with Doraemon's gadgets.",
    tags: ["Japanese", "Kids", "Adventure", "Movie"],
    popularity: "medium",
  },

  // ══════════════════════════════════════════════
  // AMERICAN / INTERNATIONAL CARTOONS (HINDI DUB)
  // ══════════════════════════════════════════════
  {
    id: "tom-jerry",
    title: "Tom and Jerry",
    displayTitle: "Tom and Jerry",
    image: "",
    synopsis: "A cat and mouse engage in endless slapstick battles.",
    genres: ["Comedy", "Slapstick"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 161,
    seasons: 13,
    status: "airing",
    releaseYear: 1940,
    rating: "U",
    studio: "Metro-Goldwyn-Mayer",
    description: "Tom and Jerry is an American animated series about the comedic rivalry between a cat named Tom and a mouse named Jerry.",
    tags: ["American", "Kids", "Comedy", "Classic", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "ben-10",
    title: "Ben 10",
    displayTitle: "Ben 10",
    image: "",
    synopsis: "A boy discovers an alien watch that lets him transform into different aliens.",
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    network: "Cartoon Network India",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "USA",
    totalEpisodes: 200,
    seasons: 10,
    status: "airing",
    releaseYear: 2016,
    rating: "U",
    studio: "Cartoon Network Studios",
    dubPlatform: "Cartoon Network India",
    description: "Ben 10 follows Ben Tennyson, a boy who discovers an alien watch called the Omnitrix that allows him to transform into ten different alien species.",
    tags: ["American", "Kids", "Action", "Sci-Fi", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "scooby-doo",
    title: "Scooby-Doo",
    displayTitle: "Scooby-Doo, Where Are You!",
    image: "",
    synopsis: "A group of friends and their talking dog solve mysteries.",
    genres: ["Comedy", "Mystery", "Adventure"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 400,
    seasons: 30,
    status: "airing",
    releaseYear: 1969,
    rating: "U",
    studio: "Hanna-Barbera",
    description: "Scooby-Doo follows a group of teenage mystery solvers and their talking Great Dane dog Scooby-Doo as they investigate supernatural mysteries.",
    tags: ["American", "Kids", "Comedy", "Mystery", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "spongebob",
    title: "SpongeBob SquarePants",
    displayTitle: "SpongeBob SquarePants",
    image: "",
    synopsis: "A sponge lives in a pineapple under the sea and works at a fast food restaurant.",
    genres: ["Comedy", "Slice of Life"],
    network: "Nickelodeon India",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "USA",
    totalEpisodes: 300,
    seasons: 15,
    status: "airing",
    releaseYear: 1999,
    rating: "U",
    studio: "Nickelodeon Animation Studio",
    dubPlatform: "Nickelodeon India",
    description: "SpongeBob SquarePants follows the adventures of a yellow sea sponge who lives in a pineapple under the sea and works as a fry cook at the Krusty Krab.",
    tags: ["American", "Kids", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "powerpuff-girls",
    title: "The Powerpuff Girls",
    displayTitle: "The Powerpuff Girls",
    image: "",
    synopsis: "Three kindergarten-aged girls with superpowers fight crime.",
    genres: ["Action", "Comedy", "Sci-Fi"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 138,
    seasons: 6,
    status: "completed",
    releaseYear: 2016,
    rating: "U",
    studio: "Cartoon Network Studios",
    dubPlatform: "Cartoon Network India",
    description: "The Powerpuff Girls follows three kindergarten-aged girls with superpowers as they protect the city of Townsville from various villains.",
    tags: ["American", "Kids", "Action", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "dexters-lab",
    title: "Dexter's Laboratory",
    displayTitle: "Dexter's Laboratory",
    image: "",
    synopsis: "A boy genius hides his secret laboratory from his family.",
    genres: ["Comedy", "Sci-Fi"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 224,
    seasons: 4,
    status: "completed",
    releaseYear: 1996,
    rating: "U",
    studio: "Hanna-Barbera",
    dubPlatform: "Cartoon Network India",
    description: "Dexter's Laboratory follows a boy genius named Dexter who has a secret laboratory filled with inventions, which his sister Dee Dee constantly invades.",
    tags: ["American", "Kids", "Comedy", "Sci-Fi", "Classic", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "oggy-cockroaches",
    title: "Oggy and the Cockroaches",
    displayTitle: "Oggy and the Cockroaches",
    image: "",
    synopsis: "A blue cat tries to live peacefully but three cockroaches constantly annoy him.",
    genres: ["Comedy", "Slapstick"],
    network: "Sony YAY",
    language: ["Hindi", "English"],
    country: "France",
    totalEpisodes: 428,
    seasons: 8,
    status: "airing",
    releaseYear: 1998,
    rating: "U",
    studio: "Gaumont Multimedia",
    description: "Oggy and the Cockroaches follows a blue cat named Oggy who tries to live peacefully but is constantly tormented by three mischievous cockroaches.",
    tags: ["French", "Kids", "Comedy", "Slapstick", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "kung-fu-panda",
    title: "Kung Fu Panda: Legends of Awesomeness",
    displayTitle: "Kung Fu Panda",
    image: "",
    synopsis: "Po the panda trains to become a kung fu master.",
    genres: ["Action", "Comedy", "Martial Arts"],
    network: "Nickelodeon India",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "USA",
    totalEpisodes: 81,
    seasons: 4,
    status: "completed",
    releaseYear: 2011,
    rating: "U",
    studio: "DreamWorks Animation",
    dubPlatform: "Nickelodeon India",
    description: "Kung Fu Panda: Legends of Awesomeness follows Po the panda as he trains to become a kung fu master and protects the Valley of Peace.",
    tags: ["American", "Kids", "Action", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "phineas-ferb",
    title: "Phineas and Ferb",
    displayTitle: "Phineas and Ferb",
    image: "",
    synopsis: "Two stepbrothers build incredible inventions during summer vacation.",
    genres: ["Comedy", "Adventure", "Sci-Fi", "Musical"],
    network: "Disney India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 222,
    seasons: 4,
    status: "completed",
    releaseYear: 2007,
    rating: "U",
    studio: "Walt Disney Television Animation",
    dubPlatform: "Disney India",
    description: "Phineas and Ferb follows two stepbrothers who build incredible inventions during their summer vacation while their sister Candace tries to bust them.",
    tags: ["American", "Kids", "Comedy", "Disney", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "gravity-falls",
    title: "Gravity Falls",
    displayTitle: "Gravity Falls",
    image: "",
    synopsis: "Twins uncover mysterious secrets in a weird Oregon town.",
    genres: ["Comedy", "Mystery", "Adventure", "Fantasy"],
    network: "Disney India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 40,
    seasons: 2,
    status: "completed",
    releaseYear: 2012,
    rating: "UA",
    studio: "Walt Disney Television Animation",
    dubPlatform: "Disney India",
    description: "Gravity Falls follows twins Dipper and Mabel Pines as they spend summer with their great-uncle Stan in the mysterious town of Gravity Falls, Oregon.",
    tags: ["American", "Kids", "Mystery", "Comedy", "Disney", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "avatar-last-airbender",
    title: "Avatar: The Last Airbender",
    displayTitle: "Avatar: The Last Airbender",
    image: "",
    synopsis: "A young boy must master all four elements to save the world.",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    network: "JioHotstar",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 61,
    seasons: 3,
    status: "completed",
    releaseYear: 2005,
    rating: "UA",
    studio: "Nickelodeon Animation Studio",
    dubPlatform: "JioHotstar",
    description: "Avatar: The Last Airbender follows Aang, a young boy who must master all four elements to save the world from the Fire Nation.",
    tags: ["American", "Kids", "Action", "Adventure", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "dora-explorer",
    title: "Dora the Explorer",
    displayTitle: "Dora the Explorer",
    image: "",
    synopsis: "A young Latina girl goes on adventures with her monkey friend.",
    genres: ["Adventure", "Comedy", "Educational"],
    network: "Nickelodeon India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 178,
    seasons: 8,
    status: "completed",
    releaseYear: 2000,
    rating: "U",
    studio: "Nickelodeon Animation Studio",
    dubPlatform: "Nickelodeon India",
    description: "Dora the Explorer follows a young Latina girl who goes on adventures with her monkey friend Boots, solving puzzles and learning along the way.",
    tags: ["American", "Kids", "Adventure", "Educational", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "johnny-bravo",
    title: "Johnny Bravo",
    displayTitle: "Johnny Bravo",
    image: "",
    synopsis: "A muscular, vain man constantly fails at picking up women.",
    genres: ["Comedy", "Action"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 67,
    seasons: 4,
    status: "completed",
    releaseYear: 1997,
    rating: "U",
    studio: "Hanna-Barbera",
    dubPlatform: "Cartoon Network India",
    description: "Johnny Bravo follows a muscular, vain man who constantly fails at picking up women and gets into hilarious situations.",
    tags: ["American", "Kids", "Comedy", "Classic", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "the-kids-next-door",
    title: "Codename: Kids Next Door",
    displayTitle: "Codename: Kids Next Door",
    image: "",
    synopsis: "A group of kids fight adult tyranny with elaborate gadgets.",
    genres: ["Action", "Comedy", "Adventure"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 78,
    seasons: 6,
    status: "completed",
    releaseYear: 2002,
    rating: "U",
    studio: "Cartoon Network Studios",
    dubPlatform: "Cartoon Network India",
    description: "Codename: Kids Next Door follows a group of kids who use elaborate gadgets and treehouses to fight adult tyranny.",
    tags: ["American", "Kids", "Action", "Comedy", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "the-smurfs",
    title: "The Smurfs",
    displayTitle: "The Smurfs",
    image: "",
    synopsis: "Small blue creatures live in mushroom houses and avoid an evil wizard.",
    genres: ["Comedy", "Adventure", "Fantasy"],
    network: "Sony YAY",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 258,
    seasons: 9,
    status: "completed",
    releaseYear: 1981,
    rating: "U",
    studio: "Hanna-Barbera",
    description: "The Smurfs follows the adventures of small blue creatures who live in mushroom houses and try to avoid being captured by the evil wizard Gargamel.",
    tags: ["American", "Kids", "Comedy", "Fantasy", "Classic", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "popeye",
    title: "Popeye the Sailor",
    displayTitle: "Popeye",
    image: "",
    synopsis: "A sailor gains super strength from eating spinach.",
    genres: ["Action", "Comedy", "Adventure"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 231,
    seasons: 6,
    status: "completed",
    releaseYear: 1960,
    rating: "U",
    studio: "Fleischer Studios",
    description: "Popeye the Sailor is an American animated series about a sailor man who gains superhuman strength by eating spinach.",
    tags: ["American", "Kids", "Action", "Classic", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "lilo-stitch",
    title: "Lilo & Stitch: The Series",
    displayTitle: "Lilo & Stitch",
    image: "",
    synopsis: "A girl and her alien pet get into adventures in Hawaii.",
    genres: ["Comedy", "Adventure", "Sci-Fi"],
    network: "Disney India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 65,
    seasons: 3,
    status: "completed",
    releaseYear: 2003,
    rating: "U",
    studio: "Walt Disney Animation Studios",
    dubPlatform: "Disney India",
    description: "Lilo & Stitch: The Series follows a young Hawaiian girl named Lilo and her alien pet Stitch as they get into various adventures.",
    tags: ["American", "Kids", "Comedy", "Disney", "Hindi Dub"],
    popularity: "medium",
  },
];

export const TOON_STATS = {
  totalCartoons: TOONS_DATABASE.length,
  indianOriginals: TOONS_DATABASE.filter(t => t.country === "India").length,
  internationalPopular: TOONS_DATABASE.filter(t => t.country !== "India").length,
  airingShows: TOONS_DATABASE.filter(t => t.status === "airing").length,
  networks: [...new Set(TOONS_DATABASE.map(t => t.network))],
  lastUpdated: new Date().toISOString().split("T")[0],
} as const;
