export interface CartoonEntry {
  id: string;
  title: string;
  displayTitle: string;
  image: string;
  synopsis: string;
  genres: string[];
  network: string;
  language: string[];
  country: string;
  totalEpisodes?: number;
  seasons?: number;
  status: "airing" | "completed" | "hiatus";
  releaseYear: number;
  endYear?: number;
  rating: string;
  creator?: string;
  studio?: string;
  dubPlatform?: string;
  description: string;
  tags: string[];
  popularity?: "high" | "medium" | "low";
}

export const TOONS_DATABASE: CartoonEntry[] = [
  // ══════════════════════════════════════════════
  // INDIAN ORIGINAL CARTOONS
  // ══════════════════════════════════════════════
  {
    id: "chhota-bheem",
    title: "Chhota Bheem",
    displayTitle: "Chhota Bheem",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "A strong young boy protects the village of Dholakpur from various threats.",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    network: "Green Gold Animation",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "India",
    totalEpisodes: 600,
    seasons: 12,
    status: "airing",
    releaseYear: 2008,
    rating: "U",
    creator: "Rajiv Chilaka",
    studio: "Green Gold Animation",
    description: "Chhota Bheem is one of India's most popular animated characters. The series follows Bheem, a strong and kind-hearted boy, and his friends as they protect the kingdom of Dholakpur from various villains and challenges. The show has spawned multiple movies, specials, and merchandise.",
    tags: ["Indian", "Kids", "Action", "Comedy", "Popular"],
    popularity: "high",
  },
  {
    id: "motu-patlu",
    title: "Motu Patlu",
    displayTitle: "Motu Patlu",
    image: "https://upload.wikimedia.org/wikipedia/en/8/8e/Motu_Patlu.png",
    synopsis: "Two best friends, Motu and Patlu, get into various comedic adventures in Furfuri Nagar.",
    genres: ["Comedy", "Slice of Life"],
    network: "Nickelodeon India",
    language: ["Hindi", "Tamil", "Telugu"],
    country: "India",
    totalEpisodes: 400,
    seasons: 8,
    status: "airing",
    releaseYear: 2012,
    rating: "U",
    creator: "Niraj Vikram",
    studio: "Cosmos-Maya",
    description: "Motu Patlu is a popular Indian animated comedy series featuring two best friends - Motu, a fat man who loves samosas, and Patlu, a thin and intelligent man. Together they get into various comedic situations in the fictional city of Furfuri Nagar.",
    tags: ["Indian", "Kids", "Comedy", "Popular"],
    popularity: "high",
  },
  {
    id: "lotta-khorn",
    title: "Lotta Khorn",
    displayTitle: "Lotta Khorn",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "A young girl with special powers protects her village.",
    genres: ["Adventure", "Comedy", "Fantasy"],
    network: "Green Gold Animation",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 150,
    seasons: 3,
    status: "completed",
    releaseYear: 2013,
    rating: "U",
    creator: "Rajiv Chilaka",
    studio: "Green Gold Animation",
    description: "Lotta Khorn follows the adventures of a young girl with special powers as she protects her village from various threats.",
    tags: ["Indian", "Kids", "Adventure"],
    popularity: "medium",
  },
  {
    id: "band-baja-bandh",
    title: "Band Baja Bandh",
    displayTitle: "Band Baja Bandh",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "A group of friends form a band and go on musical adventures.",
    genres: ["Comedy", "Music", "Slice of Life"],
    network: "Green Gold Animation",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 100,
    seasons: 2,
    status: "completed",
    releaseYear: 2015,
    rating: "U",
    studio: "Green Gold Animation",
    description: "Band Baja Bandh follows a group of friends who form a band and go on various musical adventures.",
    tags: ["Indian", "Kids", "Music"],
    popularity: "low",
  },
  {
    id: "krishna-balram",
    title: "Krishna Balram",
    displayTitle: "Krishna Balram",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "The adventures of young Krishna and Balram in Vrindavan.",
    genres: ["Adventure", "Comedy", "Mythology"],
    network: "Green Gold Animation",
    language: ["Hindi", "Tamil", "Telugu"],
    country: "India",
    totalEpisodes: 200,
    seasons: 4,
    status: "completed",
    releaseYear: 2009,
    rating: "U",
    creator: "Rajiv Chilaka",
    studio: "Green Gold Animation",
    description: "Krishna Balram depicts the childhood adventures of Lord Krishna and Balram in the beautiful land of Vrindavan, showcasing their playful nature and divine powers.",
    tags: ["Indian", "Kids", "Mythology", "Action"],
    popularity: "medium",
  },
  {
    id: "happy-family",
    title: "Happy Family: Conditions Apply",
    displayTitle: "Happy Family",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "The hilarious misadventures of a middle-class Indian family.",
    genres: ["Comedy", "Slice of Life"],
    network: "Disney India",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 150,
    seasons: 3,
    status: "completed",
    releaseYear: 2018,
    rating: "U",
    studio: "Disney India",
    description: "Happy Family follows the daily misadventures of a typical middle-class Indian family, showcasing their unique personalities and hilarious situations.",
    tags: ["Indian", "Kids", "Comedy", "Family"],
    popularity: "medium",
  },
  {
    id: "tik-tak-tail",
    title: "Tik Tak Tail",
    displayTitle: "Tik Tak Tail",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "Two unlikely friends - a clever rabbit and a not-so-smart fox - go on adventures.",
    genres: ["Comedy", "Adventure"],
    network: "Amazon Prime Video",
    language: ["Hindi", "English"],
    country: "India",
    totalEpisodes: 78,
    seasons: 2,
    status: "completed",
    releaseYear: 2018,
    rating: "U",
    studio: "Toonzone Studios",
    description: "Tik Tak Tail follows the hilarious adventures of Tik, a clever rabbit, and Tak, a not-so-smart fox, as they navigate through various challenges.",
    tags: ["Indian", "Kids", "Comedy"],
    popularity: "low",
  },
  {
    id: "lambu-motu",
    title: "Lambu Motu Tingu Tong",
    displayTitle: "Lambu Motu Tingu Tong",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "The adventures of two friends - Lambu and Motu - in their village.",
    genres: ["Comedy", "Slice of Life"],
    network: "Sony YAY",
    language: ["Hindi"],
    country: "India",
    totalEpisodes: 100,
    seasons: 2,
    status: "completed",
    releaseYear: 2017,
    rating: "U",
    studio: "Cosmos-Maya",
    description: "Lambu Motu Tingu Tong is a comedy series about two friends and their funny adventures in a village setting.",
    tags: ["Indian", "Kids", "Comedy"],
    popularity: "low",
  },
  {
    id: "rudra",
    title: "Rudra: The Rise of the Black Sun",
    displayTitle: "Rudra",
    image: "https://upload.wikimedia.org/wikipedia/en/5/56/Chhota_Bheem.jpg",
    synopsis: "A young prince battles dark forces to save his kingdom.",
    genres: ["Action", "Adventure", "Fantasy"],
    network: "Amazon Prime Video",
    language: ["Hindi", "English"],
    country: "India",
    totalEpisodes: 26,
    seasons: 1,
    status: "completed",
    releaseYear: 2020,
    rating: "UA",
    studio: "Firefly Cartoon Studio",
    description: "Rudra follows a young prince who must battle dark forces and ancient evils to protect his kingdom from destruction.",
    tags: ["Indian", "Action", "Fantasy", "Adventure"],
    popularity: "medium",
  },

  // ══════════════════════════════════════════════
  // INTERNATIONAL CARTOONS POPULAR IN INDIA
  // ══════════════════════════════════════════════
  {
    id: "doraemon",
    title: "Doraemon",
    displayTitle: "Doraemon",
    image: "https://cdn.myanimelist.net/images/anime/1859/112864.jpg",
    synopsis: "A robotic cat from the future helps a young boy with gadgets.",
    genres: ["Comedy", "Sci-Fi", "Slice of Life"],
    network: "JioHotstar",
    language: ["Hindi", "Tamil", "Telugu", "English", "Japanese"],
    country: "Japan",
    totalEpisodes: 1787,
    seasons: 25,
    status: "airing",
    releaseYear: 2005,
    rating: "U",
    studio: "Shin-Ei Animation",
    dubPlatform: "JioHotstar",
    description: "Doraemon is a Japanese manga and anime series about a robotic cat named Doraemon who travels back in time from the 22nd century to help a young boy named Nobita Nobi with his problems using futuristic gadgets.",
    tags: ["Japanese", "Kids", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "shin-chan",
    title: "Shin-chan",
    displayTitle: "Crayon Shin-chan",
    image: "https://cdn.myanimelist.net/images/anime/1726/109342.jpg",
    synopsis: "A mischievous 5-year-old causes chaos wherever he goes.",
    genres: ["Comedy", "Slice of Life"],
    network: "JioHotstar",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "Japan",
    totalEpisodes: 1100,
    seasons: 20,
    status: "airing",
    releaseYear: 1992,
    rating: "U",
    studio: "Shin-Ei Animation",
    dubPlatform: "JioHotstar",
    description: "Crayon Shin-chan follows the adventures of Shinnosuke Nohara, a 5-year-old boy known for his inappropriate behavior, love of action masked rider, and his catchphrases.",
    tags: ["Japanese", "Kids", "Comedy", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "pokemon",
    title: "Pokemon",
    displayTitle: "Pokemon",
    image: "https://cdn.myanimelist.net/images/anime/4/85598.jpg",
    synopsis: "Ash Ketchum travels the world catching and training Pokemon.",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    network: "Cartoon Network India",
    language: ["Hindi", "English"],
    country: "Japan",
    totalEpisodes: 1250,
    seasons: 25,
    status: "airing",
    releaseYear: 1997,
    rating: "U",
    studio: "OLM",
    dubPlatform: "Cartoon Network India",
    description: "Pokemon follows Ash Ketchum as he travels through various regions, catching and training Pokemon while striving to become a Pokemon Master.",
    tags: ["Japanese", "Kids", "Action", "Adventure", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "ben-10",
    title: "Ben 10",
    displayTitle: "Ben 10",
    image: "https://upload.wikimedia.org/wikipedia/en/c/c3/Ben_10_logo.svg",
    synopsis: "A boy discovers an alien watch that lets him transform into different aliens.",
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    network: "Cartoon Network India",
    language: ["Hindi", "Tamil", "Telugu", "English"],
    country: "USA",
    totalEpisodes: 200,
    seasons: 10,
    status: "airing",
    releaseYear: 2016,
    rating: "U",
    studio: "Cartoon Network Studios",
    dubPlatform: "Cartoon Network India",
    description: "Ben 10 follows Ben Tennyson, a boy who discovers an alien watch called the Omnitrix that allows him to transform into ten different alien species.",
    tags: ["American", "Kids", "Action", "Sci-Fi", "Popular", "Hindi Dub"],
    popularity: "high",
  },
  {
    id: "avengers-mighty-heroes",
    title: "Avengers: Mighty Heroes",
    displayTitle: "Avengers: Mighty Heroes",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Avengers_logo.png",
    synopsis: "The Avengers team up to save the world from various villains.",
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    network: "Disney India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 52,
    seasons: 2,
    status: "completed",
    releaseYear: 2010,
    rating: "U",
    studio: "Marvel Animation",
    dubPlatform: "Disney India",
    description: "The Avengers: Earth's Mightiest Heroes follows Earth's mightiest superheroes as they battle supervillains and protect the world.",
    tags: ["American", "Kids", "Action", "Marvel", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "star-wars-clonewars",
    title: "Star Wars: The Clone Wars",
    displayTitle: "Star Wars: The Clone Wars",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Star_Wars_Logo.svg",
    synopsis: "The Jedi Knights fight in the Clone Wars across the galaxy.",
    genres: ["Action", "Adventure", "Drama", "Sci-Fi"],
    network: "Disney India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 133,
    seasons: 7,
    status: "completed",
    releaseYear: 2008,
    rating: "UA",
    studio: "Lucasfilm Animation",
    dubPlatform: "Disney India",
    description: "Star Wars: The Clone Wars follows the Jedi Knights as they lead the Republic's clone army against the Separatist forces during the Clone Wars.",
    tags: ["American", "Sci-Fi", "Action", "Star Wars", "Hindi Dub"],
    popularity: "medium",
  },
  {
    id: "spider-man-animated",
    title: "Spider-Man (Animated)",
    displayTitle: "Spider-Man",
    image: "https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png",
    synopsis: "Peter Parker balances high school life with being Spider-Man.",
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    network: "Disney India",
    language: ["Hindi", "English"],
    country: "USA",
    totalEpisodes: 100,
    seasons: 3,
    status: "completed",
    releaseYear: 2017,
    rating: "U",
    studio: "Marvel Animation",
    dubPlatform: "Disney India",
    description: "Spider-Man follows Peter Parker as he balances his high school life with his responsibilities as the web-slinging superhero Spider-Man.",
    tags: ["American", "Kids", "Action", "Marvel", "Hindi Dub"],
    popularity: "medium",
  },
];

export const TOON_STATS = {
  totalCartoons: TOONS_DATABASE.length,
  indianOriginals: TOONS_DATABASE.filter(t => t.country === "India").length,
  internationalPopular: TOONS_DATABASE.filter(t => t.country !== "India").length,
  airingShows: TOONS_DATABASE.filter(t => t.status === "airing").length,
  networks: [...new Set(TOONS_DATABASE.map(t => t.network))],
  lastUpdated: "2026-07-22",
} as const;
