import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://zyniverse.vercel.app";
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: baseUrl, lastModified: now, changeFrequency: "daily", priority: 1 },
    { url: `${baseUrl}/search`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${baseUrl}/browse`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/manga`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${baseUrl}/light-novels`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${baseUrl}/schedule`, lastModified: now, changeFrequency: "weekly", priority: 0.6 },
    { url: `${baseUrl}/seasonal`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${baseUrl}/filler`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${baseUrl}/dubbed`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/indian-dubs`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/watch-order`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/watchlist`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${baseUrl}/login`, lastModified: now, changeFrequency: "monthly", priority: 0.3 },
    { url: `${baseUrl}/register`, lastModified: now, changeFrequency: "monthly", priority: 0.3 },
    { url: `${baseUrl}/premium`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${baseUrl}/developer`, lastModified: now, changeFrequency: "weekly", priority: 0.6 },
    { url: `${baseUrl}/docs`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${baseUrl}/community`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${baseUrl}/leaderboard`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${baseUrl}/awards`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${baseUrl}/critiques`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${baseUrl}/characters`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/voice-actors`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/voice-actors/indian`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/voice-lines`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/ost`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/quiz`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${baseUrl}/quiz/daily`, lastModified: now, changeFrequency: "daily", priority: 0.5 },
    { url: `${baseUrl}/conventions`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/cosplay`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${baseUrl}/doujinshi`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${baseUrl}/watch-party`, lastModified: now, changeFrequency: "weekly", priority: 0.4 },
    { url: `${baseUrl}/forum`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${baseUrl}/blog`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${baseUrl}/clubs`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${baseUrl}/challenges`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${baseUrl}/tierlist`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${baseUrl}/achievements`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${baseUrl}/activity`, lastModified: now, changeFrequency: "daily", priority: 0.4 },
    { url: `${baseUrl}/notifications`, lastModified: now, changeFrequency: "monthly", priority: 0.3 },
    { url: `${baseUrl}/news`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${baseUrl}/recommendations`, lastModified: now, changeFrequency: "weekly", priority: 0.6 },
    { url: `${baseUrl}/random`, lastModified: now, changeFrequency: "weekly", priority: 0.4 },
    { url: `${baseUrl}/status`, lastModified: now, changeFrequency: "monthly", priority: 0.3 },
    { url: `${baseUrl}/privacy`, lastModified: now, changeFrequency: "monthly", priority: 0.2 },
    { url: `${baseUrl}/terms`, lastModified: now, changeFrequency: "monthly", priority: 0.2 },
    { url: `${baseUrl}/stats`, lastModified: now, changeFrequency: "weekly", priority: 0.6 },
    { url: `${baseUrl}/calendar`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${baseUrl}/themes`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
  ];

  return staticPages;
}
